### PR TITLE
Features/expansion model

### PR DESCRIPTION
**Pull request by simnh**
This will add two things: 

* Periods for OperationalModel
* An ExpansionModel (including ExpansionFlow etc)

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
I would like to merge https://github.com/oemof/oemof/pull/303 first and integrate the changes in this branch later.

If required I can resolve conflicts and maybe we can then discuss and merge it "live in the office" tomorrow.

**Comment by uvchik** [comment]
You changed the example. Does it means, that it will break the API for those, who use additional classes/constraints.

**Comment by ckaldemeyer** [comment]
> I would like to merge #303 first and integrate the changes in this branch later.
> 
> If required I can resolve conflicts and maybe we can then discuss and merge it "live in the office" tomorrow.

I have merge the dev and resolved the conflicts.

But all tests including constraint tests are not running:

	cord@cord-Laptop:~/Programmierung/oemof/examples$ py3 oemof_full_check.py 
	WARNING:root:Optimization with unknown termination condition. Writing output anyway...
	Check Storage invest example...
	WARNING:root:Optimization with unknown termination condition. Writing output anyway...
	Check Simple least costs optimization...
	WARNING:root:Optimization with unknown termination condition. Writing output anyway...
	Check Flexible Modelling...
	WARNING:root:Graph plots do not work unless 'networkx' is installed.
	WARNING:root:Optimization with unknown termination condition. Writing output anyway...
	Check Dispatch model with csv reader...
	WARNING:root:Optimization with unknown termination condition. Writing output anyway...
	Check Investment model with csv reader...
	WARNING:root:Optimization with unknown termination condition. Writing output anyway...
	Check Variable CHP example...
	12:38:47-INFO-Path for logging: /home/cord/.oemof/log_files
	12:38:47-INFO-Used oemof version: 1506a7c3@features/expansion-model
	12:38:47-INFO-*********************************************
	12:38:47-INFO-Variable CHP example
	12:38:47-INFO-Used solver: cbc
	12:38:47-INFO-Run check: Failed
	12:38:47-INFO-Result check: Failed
	12:38:47-ERROR-"Error accessing indexed component: Index '(<oemof.solph.network.Bus object at 0x7fa4b33191b0>, <oemof.solph.network.Sink object at 0x7fa4b3319e10>, 0)' is not valid for array component 'flow'"
	12:38:47-INFO-*********************************************
	12:38:47-INFO-Simple least costs optimization
	12:38:47-INFO-Used solver: cbc
	12:38:47-INFO-Run check: Failed
	12:38:47-INFO-Result check: Failed
	12:38:47-ERROR-"Error accessing indexed component: Index '(<oemof.solph.network.LinearTransformer object at 0x7fa4b5fa8558>, <oemof.solph.network.Bus object at 0x7fa4b5fa8168>, 0)' is not valid for array component 'flow'"
	12:38:47-INFO-*********************************************
	12:38:47-INFO-Flexible Modelling
	12:38:47-INFO-Used solver: cbc
	12:38:47-INFO-Run check: Failed
	12:38:47-INFO-Result check: Failed
	12:38:47-ERROR-"Error accessing indexed component: Index '(<oemof.solph.network.LinearTransformer object at 0x7fa4b518a6c0>, <oemof.solph.network.Bus object at 0x7fa4b518a3a8>, 0)' is not valid for array component 'flow'"

Did you test it?

Additionally, the are heaps of PEP8 violations in `models.py` which I have already seen. Neverteless, it's a great feature!

**Comment by simnh** [comment]
I know, this is from my local old computer. I just pushed. I really like the Periods feature, and as we mentioned it in the abstract, i like to add a expansion model, but it definitely needs a lot of polishing (if thats still the right word)

**Comment by ckaldemeyer** [comment]
> I know, this is from my local old computer. I just pushed. I really like the Periods feature, and as we mentioned it in the abstract, i like to add a expansion model, but it definitely needs a lot of polishing (if thats still the right word)

It's really cool. Let's discuss it tomorrow, do some testing, ...

**Comment by simnh** [comment]
close in favor of #342

**Pull request closed without merging**
