### PR TITLE
Features/travis ci

### PR DESCRIPTION
**Pull request by birgits**

### CODE REVIEW

**Comment by gplssm** [comment]
Tests pass with if Python 3.3 is omitted. Shall we exclude Python 3.3 from test cases?

**Comment by gplssm** [comment]
After @gnn fixes #155 re-add Python 3.3 to .travis.yml

**Comment by uvchik** [comment]
@gplssm Will you merge it?

**Comment by gplssm** [comment]
Yes, I'll do it, when @gnn gives his OK.

**Comment by uvchik** [comment]
To reduce the server load, we could delete the push-test. I think the PR-test is enough.

**Comment by gplssm** [comment]
I disabled "Build pushes" only "Build PR" is active. If you uncomfortable with this, we can reconfigure it...

**Comment by uvchik** [comment]
> I disabled "Build pushes" only "Build PR" is active. If you uncomfortable with this, we can reconfigure it...

@gplssm : Where did you do it? Did you push it? I do not see a commit.

**Comment by gplssm** [comment]
I disabled in the config on the travis website which is not visible in the commit history.

**Comment by uvchik** [comment]
But there are still two checks (continuous-integration/travis-ci/push and continuous-integration/travis-ci/pr) or do I misunderstand something?

**Comment by gplssm** [comment]
We still see 2 tests here because my changes in the settings are older then the last commit in this PR. Have a look at PR #159, where only one test run is shown.

**Pull request merged**
