### PR TITLE
remove matplotlib requirement and adapt graph tools

### PR DESCRIPTION
**Pull request by uvchik**
* matplotlib was removed from the requirements because plotting function was moved to oemof-visio
* do not throw warnings unless the function is used 
     - matplotlib warning only if `plot=True`
     - graph-tool warnings only if graph function is used
* Test import of each package separately and throw separate logging-error
* clean code
* integrate changes from #424 
* Related to #418

### CODE REVIEW

**Comment by uvchik** [comment]
Sorry, I messed around a little bit because the tests work locally but not with Travis, so I had to push every little change and try again.

Now everything works but I think we should split this function.

One function that creates the network graph. One can make network analyses with this graph and I am not sure if the outputlib is the right place.

A second function that draws the graph. This function could be part of the outputlib or even oemof-visio because we decided that we do not want to have plotting function within oemof.

@ckaldemeyer @oemof/oemof-solph What do you think?

**Comment by ckaldemeyer** [comment]
> Sorry, I messed around a little bit because the tests work locally but not with Travis, so I had to push every little change and try again.
> 
> Now everything works but I think we should split this function.
> 
> One function that creates the network graph. One can make network analyses with this graph and I am not sure if the outputlib is the right place. The tools module might be a better place.
> 
> A second function that draws the graph. This function could be part of the outputlib or even part of oemof-visio because we decided that we do not want to have plotting functions within oemof.
> 
> @ckaldemeyer @oemof/oemof-solph What do you think?

Thanks for your effort! I strongly support this.

**Comment by uvchik** [comment]
After I talked to @ckaldemeyer I implemented the suggestions from above.

* The graph function is divided into `graph()` and `draw_graph()`.
* `draw_graph()` is deprecated and will be removed with the next major release (or with this release if we get a fast decision - see below)
* The `networkx` is now a requirement of oemof, while `matplotlib` was removed as a requirement.

Open questions:

* Is the outputlib a good place for a graph tool, if it can be used to locate unconnected nodes etc.? I think we should move it into the tools or the core section.
* Where shall we move the `draw_graph()` function? oemof-visio, examples....

A good place for the graph tools might be interesting to clearly differentiate the model part from the graph part.

@oemof/oemof-core / @oemof/oemof-solph 
If get a fast decision we can move it within the v0.2. release. Otherwise we will do it later.

**Comment by ckaldemeyer** [comment]
> After I talked to @ckaldemeyer I implemented the suggestions from above.
> 
>     The graph function is divided into graph() and draw_graph().
>     draw_graph() is deprecated and will be removed with the next major release (or with this release if we get a fast decision - see below)
>     The networkx is now a requirement of oemof, while matplotlib was removed as a requirement.

Thanks!

> Is the outputlib a good place for a graph tool, if it can be used to locate unconnected nodes etc.? I think we should move it into the tools or the core section

I would also vote for tools.

> Where shall we move the draw_graph() function? oemof-visio, examples....

Depending on the usage frequency start with examples and move to visio if people need it more often.

> @oemof/oemof-core / @oemof/oemof-solph
> If get a fast decision we can move it within the v0.2. release. Otherwise we will do it later.

I vote for v.0.2!

**Comment by uvchik** [comment]
> I vote for v.0.2!

Okay, let's wait for a response of @simnh.

**Comment by simnh** [comment]
I am  fine, though this could also just be a function that is integrated in  the core energysystem as a method...but even therefore it can stay in the outputlib

**Comment by simnh** [comment]
I think also it make sense to name it: create_nx_grahp or somthing, as the graph is already defined in a oemof logic...

**Comment by ckaldemeyer** [comment]
> I am fine, though this could also just be a function that is integrated in the core energysystem as a method...but even therefore it can stay in the outputlib

We could easily use the function from `tools` within a method of the  `es` class first and transfer it to the class afterwards. What do you think?

**Comment by ckaldemeyer** [comment]
> I am fine, though this could also just be a function that is integrated in the core energysystem as a method...but even therefore it can stay in the outputlib
> 
> We could easily use the function from tools within a method of the es class first and transfer it to the class afterwards. What do you think?

The graph creation would also work at core level and we could place it there and have one more example for our layer structure..

**Comment by uvchik** [comment]
So be it....

**Pull request merged**
