### PR TITLE
solph LOPF 

### PR DESCRIPTION
**Pull request by simnh**
Linear Optimal Powerflow for solph with custom componets

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
I think this is a nice functionality but shouldn't all nw-classes and blocks be in the `components` or `custom` module.

As I understood it yesterday:

* `network` and `blocks` -> Generic components like Sink, Source, Transformer
* `components` -> Solph components like GenericStorage (+Investment), VariableFractionTransformer, GenericCHP (integrated in solph init)
* `custom` -> Custom stuff like CAES, ....

Meanwhile I think about if integrating `blocks` into `network` would be more consistent..

**Comment by uvchik** [comment]
> Meanwhile I think about if integrating blocks into network would be more consistent..

What about moving the blocks from `blocks` to `network` and removing the `blocks` module afterwards.

**Comment by simnh** [comment]
I wrote this some time ago, @ckaldemeyer you are right, as we now have this structure I just wanted to add this pull-request and maybe someday integrate this in the new structure...

**Comment by simnh** [comment]
I do not know, it would be consistent with components.py, but I do not know if its nice to mix up solph classes with some internal pyomo constraint stuff (however we did it anyway already..so we could do this!) 

then I think we might think about the names of BinaryFlow etc as well..I'd prefer rather something like 'nonconvexities'...

**Comment by ckaldemeyer** [comment]
> Meanwhile I think about if integrating blocks into network would be more consistent..
> What about moving the blocks from blocks to network and removing the blocks module afterwards.

That's exactly what I meant :smile: 

> I do not know, it would be consistent with components.py, but I do not know if its nice to mix up solph classes with some internal pyomo constraint stuff (however we did it anyway already..so we could do this!)

Why not put them in `custom` at first. What internal constraint stuff do you mean? In `custom` it would be fine I guess..

> then I think we might think about the names of BinaryFlow etc as well..I'd prefer rather something like 'nonconvexities'...

It all depends on how we build categories. Based on the impact on the problem type (nonconvexities, ...), on real world representations, on the specific/generic usability, ...

**Comment by ckaldemeyer** [comment]
We just have to be carefull not to blow up the `custom` module up to 20.000 lines with stuff that no one needs and might not even be working anymore. 

Nonetheless, LOPF is an improvement!

**Comment by simnh** [comment]
won't be able to do it for now...

**Pull request closed without merging**
