### PR TITLE
Remove additional python package description

### PR DESCRIPTION
**Pull request by c-moeller**
I removed a paragraph describing python package installation because it's not very interesting for the oemof documention.

### CODE REVIEW

**Comment by uvchik** [comment]
There is one "Additional Python packages" section in the "Windows" section as well.

**Comment by uvchik** [comment]
👍 Thanks

**Comment by c-moeller** [comment]
Shall I merge?

**Comment by uvchik** [comment]
You selected @birgits as a reviewer so you (normally) should wait for her approval until you merge. 

On the other hand.... 😏

**Pull request merged**
