### PR TITLE
Adaptions of the docu to the new version of the outputlib.

### PR DESCRIPTION
**Pull request by jnnr**

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
Thanks for your effort!

Should we add some remarks on the structure of the result dictionary (my_results[(n1,n2)/(n1,None)]['sequences'/'scalars']?

**Comment by jnnr** [comment]
Thanks for reviewing! Indeed we should add a more detailed description.

I had to get into working with outputlib myself. I try to learn by playing with the examples. Am I right that you have to give a name to the node when you create it to be able to pick it later in the results dictionary later by [(n1, n2)] or [(n1, None)] ? In the examples, not all nodes are assigned variable names.

**Comment by uvchik** [comment]
Both is possible. You can use the name (label) or the object itself.

By default it is the object but @ckaldemeyer wrote a transformation function that converts the objects in the keys to their labels.

**Comment by jnnr** [comment]
I checked it again. Indeed both is possible, but only in views.node(). Here you can either do views.node(results, 'electricity') 
or 
views.node(results, b_el) 
for a node that is defined as
bel = solph.Bus(label='electricity')

Working with results dict directly it does only work with the variable names. Does that mean that one usually would not use the results dictionary provided by processing.results(om) directly, but only by requesting views of certain nodes?

**Comment by henhuy** [comment]
You can use strings to access results as well - therefore, you have to convert the keys of result dict to strings via `views.convert_keys_to_strings(result)` first.
The same happens in `views.node` automatically if you insert strings.
But attention! Output of `Views.node` differs on input! If you enter strings, all outputs of node results will be strings as well (no `Node` objects anymore!) - so you are losing information thereby...

**Comment by uvchik** [comment]
To access the objects you can also use `groups` of the EnergySystem.

```python
>>> es = solph.EnergySystem(....)
[....]
>>> storage = es.groups['storage_label']
>>> type(storage)
<class 'oemof.solph.components.GenericStorage'>
```

**Comment by ckaldemeyer** [comment]
> You can use strings to access results as well - therefore, you have to convert the keys of result dict to strings via views.convert_keys_to_strings(result) first.
> The same happens in views.node automatically if you insert strings.
> But attention! Output of Views.node differs on input! If you enter strings, all outputs of node results will be strings as well (no Node objects anymore!) - so you are losing information thereby...

Well, this was just how everything started during the redisign of the outputlib. If you have the feeling that a different functionality (e.g. always converting to string keys, ...) makes more sense, we can still change it.

**Comment by jnnr** [comment]
I adapted the documentation according to your comments. It seems that the most handy way to use the outputlib as it is now is using views.node() to access data belonging to nodes or groupings. 

I found the documentation of the groupings rather confusing. Searching the examples, I did not find one that uses the groupings. I will play around with this to learn how it works as soon I have the time.

**Comment by uvchik** [comment]
> I adapted the documentation according to your comments. It seems that the most handy way to use the outputlib as it is now is using views.node() to access data belonging to nodes or groupings.

I would not say that. The `views.node()` function is very convenient but I do need the direct API as well e.g. if you want to compare a special flow between regions. In that case the `views.node()` function does not help. Therefore I would describe both ways.

> I found the documentation of the groupings rather confusing. Searching the examples, I did not find one that uses the groupings. I will play around with this to learn how it works as soon I have the time.

One easy thing is that each Node object is a group itself identified by its label. So you can get any Node by using the group method `es.group['label']`. I think this is the most important functionality for users.

**Comment by uvchik** [comment]
I think processing is a better place for the conversion function (keys to labels) #417 .

**Comment by jnnr** [comment]
I expanded and reformulated the explanation again after talking with Uwe. I hope things are clearer now?

**Comment by jnnr** [comment]
@cord @uvchik: Are you ok with this? With your approval, I would merge soon.

**Comment by uvchik** [comment]
I think you can just merge. We still may fix things later.

**Comment by jnnr** [comment]
Ok, thanks!

**Comment by ckaldemeyer** [comment]
ohh.. to late ;)

**Pull request merged**
