### PR TITLE
Add investment dict to results object for easier access

### PR DESCRIPTION
**Pull request by simnh**
Accessing investment result is really annoying right now as they are located shitty. I propose adding an investment object to result dict for easier access. I know we wanted to replace the result dict anyway in future but until then... who knows

### CODE REVIEW

**Comment by simnh** [comment]
@gnn do you have a clue, why checks 3.5 fail?

**Comment by ckaldemeyer** [comment]
> Accessing investment result is really annoying right now as they are located shitty. I propose adding an investment object to result dict for easier access. I know we wanted to replace the result dict anyway in future but until then... who knows

It's still on my TODO list to make a proposal in the base of our discussion in Berlin in December. But there's quite some stuff to do atm..

So go ahead if it works quickly!

**Comment by uvchik** [comment]
The following code is from our storage invest example:
```python
    capex = 1000
    lifetime = 20
    wacc = 0.05
    epc = capex * (wacc * (1 + wacc) ** lifetime) / ((1 + wacc) ** lifetime - 1)

    # create storage transformer object for storage
    solph.Storage(
        label='storage',
        inputs={bel: solph.Flow(variable_costs=10e10)},
        outputs={bel: solph.Flow(variable_costs=10e10)},
        capacity_loss=0.00, initial_capacity=0,
        nominal_input_capacity_ratio=1/6,
        nominal_output_capacity_ratio=1/6,
        inflow_conversion_factor=1, outflow_conversion_factor=0.8,
        fixed_costs=35,
        investment=solph.Investment(ep_costs=epc))
```
I would prefer this solution:
`oemof/tools/calculations.py`
```python
def annuity(capex, lifetime, wacc):
    return capex * (wacc * (1 + wacc) ** lifetime) / ((1 + wacc) ** lifetime - 1)
```

Then the example would look like this:
```python
from oemof.tools import calculations as calc

    # create storage transformer object for storage
    solph.Storage(
        label='storage',
        inputs={bel: solph.Flow(variable_costs=10e10)},
        outputs={bel: solph.Flow(variable_costs=10e10)},
        capacity_loss=0.00, initial_capacity=0,
        nominal_input_capacity_ratio=1/6,
        nominal_output_capacity_ratio=1/6,
        inflow_conversion_factor=1, outflow_conversion_factor=0.8,
        fixed_costs=35,
        investment=solph.Investment(ep_costs=calc.annuity(capex=1000, lifetime=20, wacc=0.05))
```

Name of the function/module is not fixed, just brief ideas.

**Comment by simnh** [comment]
Ok I reverted my shitty merge. Now @ckaldemeyer  can start a new branch/ pull request and add the ideas from the last meeting in Berlin. (regarding oemof results)

**Comment by uvchik** [comment]
Will you add an investment calculation to the tools subpackage?

**Comment by ckaldemeyer** [comment]
> Ok I reverted my shitty merge. Now @ckaldemeyer can start a new branch/ pull request and add the ideas from the last meeting in Berlin. (regarding oemof results)

Some time... Where are the new developers overtaking here? ;-)

**Pull request merged**
