### PR TITLE
Change to MIT license

### PR DESCRIPTION
**Pull request by p-snft**
According to the vote in https://github.com/oemof/organisation/issues/50, we change to the MIT license.

### CODE REVIEW

**Comment by fwitte** [comment]
Do not forget the license text at the end of README. I tried to push to this branch, but could not? Do I not have write permission?

**Comment by p-snft** [comment]
@fwitte: Thanks for the reminder. (I believed you would have write access here...)

**Comment by fwitte** [comment]
```
git push
ERROR: Permission to oemof/oemof.git denied to fwitte.
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
```
Also, I can not merge the PR...

**Comment by p-snft** [comment]
If you cannot merge, you obviously do not have write access. I realised that the same applies for me for some other oemof repositories.

**Pull request merged**
