### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by jnnr**
* Describe your pull request:
We thought about introducing a little feature to make the development process easier: A pull request template that helps you structuring your description when you open a pull request and helps your reviewers and others to quickly understand what the PR is about.  

* Related issues?
#413 

* Share your knowledge: Insights/Remarks
This is a recommended feature which we could try out without a big effort. I did some little research on how people's templates look like and created this proposal. Using PRs to share the knowledge you acquired while working on that feature/piece of docu, etc. seems a good idea to me.

* Other comments and questions
If you have some suggestions, please let us know. I suggest that we try it out and see how it feels using it!

* Checklist:
  * [x] Have a look at the [teams](https://github.com/orgs/oemof/teams) to choose reviewers
    Consider inviting new developers
  * [x] Assign labels
  * [ ] For new features: Remember the documentation

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
> Describe your pull request:
> We thought about introducing a little feature to make the development process easier: A pull request template that helps you structuring your description when you open a pull request and helps your reviewers and others to quickly understand what the PR is about.
> 
> Related issues?
> #413
> 
> Share your knowledge: Insights/Remarks
> This is a recommended feature which we could try out without a big effort. I did some little research on how people's templates look like and created this proposal. Using PRs to share the knowledge you acquired while working on that feature/piece of docu, etc. seems a good idea to me.
> 
> Other comments and questions
> If you have some suggestions, please let us know. I suggest that we try it out and see how it feels using it!
> 
> Checklist:
> 
>  Have a look at the teams to choose reviewers
> Consider inviting new developers
>  Assign labels
>  For new features: Remember the documentation

Nice. Thanks!

**Comment by uvchik** [comment]
> Have a look at the teams to choose reviewers
> Consider inviting new developers
> Assign labels
> For new features: Remember the documentation

Consider that people who start pull requests with a fork may not have the right to assign developers, to set labels or choose reviewers. Anybody of the developers should do that soon, once the PR is created.

**Comment by c-moeller** [comment]
I like your proposal. I added a hint to the pull request template to the documentation: #413

**Comment by jnnr** [comment]
> Consider that people who start pull requests with a fork may not have the right to assign developers, to set labels or choose reviewers. Anybody of the developers should do that soon, once the PR is created.

So, if you are not part of oemof-devs, you cannot do that? How could we account for that? 
Like this?

If possible,
    have a look at the teams to choose reviewers
    (consider inviting new developers)
    assign labels
    for new features: Remember the documentation

**Comment by uvchik** [comment]
> If possible,
> * have a look at the teams to choose reviewers
> (consider inviting new developers)
> * assign labels
> * for new features: Remember the documentation

I think these are the tasks of the maintainer. They should know which labels are good who may be good to review the code.

Advanced contributors with push rights might do that on their own but advanced contributors should become maintainer anyway 😄

**Comment by jnnr** [comment]
Ok! In this case, I would leave those two points out and just leave one :)

> for new features: Remember the documentation!

**Comment by jnnr** [comment]
Seems like there are no other objections? If you are ok, I would merge soon.

**Pull request merged**
