### PR TITLE
Economics module in tools

### PR DESCRIPTION
**Pull request by simnh**
Some economic calculations are frequently used. I added a module to tools as suggested by @uvchik . 

We might want to add calculations based on the results structure of the oemof core layer, e.g. calculating LOC etc.

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
> Some economic calculations are frequently used. I added a module to tools as suggested by @uvchik .
> 
> We might want to add calculations based on the results structure of the oemof core layer, e.g. calculating LOC etc.

Nice! I think this is a good idea.

Bei LOC you probably mean LCOE?

**Comment by simnh** [comment]
:D well, its still morning...yes of course LCOE :)

**Comment by uvchik** [comment]
I just adapted the example to make users aware of the new function and to include it in the tests.

**Comment by ckaldemeyer** [comment]
From my side this can be merged as well

**Comment by simnh** [comment]
Such a great feature can't wait ... ;)

**Comment by ckaldemeyer** [comment]
If @uvchik is also fine he can merge

**Comment by uvchik** [comment]
I already approved 7 days ago (see above). The official approval of @ckaldemeyer and @gnn is still missing. But who cares :smirk:

**Comment by uvchik** [comment]
@simnh : Do want to write a whatsnew entry?

**Comment by ckaldemeyer** [comment]
> I already approved 7 days ago (see above). The official approval of @ckaldemeyer and @gnn is still missing. But who cares

Now it's official :smile: @simnh can add a whatsnew if he wants and merge

**Comment by uvchik** [comment]
I solved the merge conflicts.

**Pull request merged**
