### PR TITLE
Features/add csv reader example

### PR DESCRIPTION
**Pull request by ckaldemeyer**
I have added a minimal example that should explain the funtionality of the CSV-reader.

Feedback is welcome!

### CODE REVIEW

**Comment by simnh** [comment]
I think it could be smaller but for now it's ok

**Comment by ckaldemeyer** [comment]
> I think it could be smaller but for now it's ok

Do you mean the code or the energy system (regions, pps, ...)?

**Comment by ckaldemeyer** [comment]
I have now reduced the code and put the model/plotting into functions. The model function returns the objective value in a dictionary!

**Comment by uvchik** [comment]
Everything is fine now.

**Pull request merged**
