### PR TITLE
Integrate sos constraints

### PR DESCRIPTION
**Pull request by simnh**
I changed the branch name as now we are trying to integrate generic sos1/sos2 constraints as linearisation of non-linear terms.

### CODE REVIEW

**Comment by simnh** [comment]
I guess this will be on hold, until somebody else needs this functionality.

**Comment by uvchik** [comment]
Okay, I changed the milestone :smirk:

**Comment by mloenneberga** [comment]
hi, i have an interest in keeping this pull request up! I have tried to implement an efficiency curve constraint, therefore sos could be useful. @simnh : would it be possible to have a call on this topic? (maybe wed or thur next week?)

**Comment by simnh** [comment]
Ok I re-opend this one. But i may be worth thinking this from skretch within the new structure of v0.2. 

I am in on a project meeting in Groningen next week, but Wed morning might be possible. I send you a p.m.

**Comment by simnh** [comment]
or maybe you send me a message, because I don't have your mail :)

**Comment by simnh** [comment]
closed in favor of #403

**Pull request closed without merging**
