### PR TITLE
Add WHATSNEW for new components

### PR DESCRIPTION
**Pull request by ckaldemeyer**
This adds an extra chapter for new components within WHATSNEW. Feel free to merge if you are fine!

### CODE REVIEW

**Comment by uvchik** [comment]
Shall we add the difference between custom components (early stage) and and components (approved) on top and then just add (custom) or (component) in the list?

Or just merge. It is your decision.

**Comment by ckaldemeyer** [comment]
> Shall we add the difference between custom components (early stage) and and components (approved) on top and then just add (custom) or (component) in the list?
> 
> Or just merge. It is your decision.

It is enough for now and we still need room for improvements ;-)

**Comment by uvchik** [comment]
> It is enough for now and we still need room for improvements ;-)

Improvements in the whatsnew.rst - great 😆

**Comment by ckaldemeyer** [comment]
> It is enough for now and we still need room for improvements ;-)
> 
> Improvements in the whatsnew.rst - great :laughing:

Unlimited... :smile:

**Comment by uvchik** [comment]
We should talk about how to create references, see: http://oemof.readthedocs.io/en/latest/whats_new.html

**Comment by simnh** [comment]
I just realised we added a few new test, me not, but @uvchik  and @ckaldemeyer . We could add them to the WHATSNEW very briefly ...no? Just because there is a section called `Testing`

**Comment by ckaldemeyer** [comment]
> I just realised we added a few new test, me not, but @uvchik and @ckaldemeyer . We could add them to the WHATSNEW very briefly ...no? Just because there is a section called Testing

I'll add them!

**Comment by uvchik** [comment]
Thank you very much, @ckaldemeyer 🎉

**Pull request merged**
