### PR TITLE
Add BaseModel to solph 

### PR DESCRIPTION
**Pull request by simnh**
Hey I like to restructure solph models internally, to add a multi-period model at some point, which I won't merge with the existing stuff. I think this will add flexibility...

Does not change anything really for anyone except core-solph-developers ;)

I really like to merge this once for v0.2 ;)

@gnn : Would be very interested in your opinion on my code!

### CODE REVIEW

**Comment by uvchik** [comment]
> Does not change anything really for anyone except core-solph-developers ;)

This announcement was misleading, because you silently broke the API.

Please be clearer if you rename a central attribute. I took me a while to find the error 😞

**Comment by henhuy** [comment]
Why did the tests pass if API was broken?

**Comment by uvchik** [comment]
> Why did the tests pass if API was broken?

Good point, I will add a regression test.

**Comment by uvchik** [comment]
> Why did the tests pass if API was broken?

I do not have to add tests because there are already some test regarding this issue. They were fixed.

Only examples/apps failed afterwards.

**Pull request merged**
