### PR TITLE
New flow gradient API

### PR DESCRIPTION
**Pull request by simnh**
I gave it a shot but I don't know if its a good idea, kind of hackish...

from #344

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
> I gave it a shot but I don't know if its a good idea, kind of hackish...
> 
> from #344

Why do you think it is hacky?

**Comment by simnh** [comment]
Just feels like it right now :), I guess @gnn would improve this. I liked the new generic setting of attributes of the flow and now I started with a dict and messed this nice code up again..but I of course works..and the internal logic can be understood (I think)

**Comment by simnh** [comment]
As we decided to remove the csv-reader, this one can be merged, if the API is ok for everybody...please do so, if you agree @ckaldemeyer , @uvchik

**Comment by simnh** [comment]
I am not sure, when I will have the time...probably in two weeks...

**Comment by uvchik** [comment]
I added a test but either I got the API wrong or this features does not work properly.

I created the following Source object and expected the costs to be part of the objective function. You can find the resulting lp-file [here](https://github.com/oemof/oemof/blob/features/gradient-costs/tests/lp_files/source_with_gradient.lp).

```python
        bel = solph.Bus(label='electricityBus')

        solph.Source(label='powerplant', outputs={bel: solph.Flow(
            nominal_value=999, variable_costs=23,
            positive_gradient={'ub': 0.03, 'costs': 7},
            negative_gradient={'ub': 0.05, 'costs': 8})})
```

**Comment by uvchik** [comment]
@simnh What about this one?

**Comment by simnh** [comment]
i think it should be fine

**Comment by uvchik** [comment]
> i think it should be fine

You mean the `lp-file`?

And what do you think about building the objective parts?

**Comment by uvchik** [comment]
I am fine now. 

@gnn Could you have a look at the attribute definition as discussed above.

@simnh Could you have a look at commit b5a234c. These lines seem to be obsolete to me.

**Comment by gnn** [comment]
Hi there. I don't think it's (too) hackish. It's actually readable and self explanatory.
The only small "gripe" I had at first was the fact that explicit `None`s where stored in the defaults, because that is what `.get`'s differing behaviour from `[]` is for. But after thinking about it, the explicit `None`s are a good way of communicating through the code how to specify no upper bound and that this is the default.

**Pull request merged**
