### PR TITLE
Change existing test to make it fail

### PR DESCRIPTION
**Pull request by uvchik**
It should be possible to use tuple and(!) string labels in one EnergySystem. At the moment it is only possible to use either string or tuple labels.

If you mix them you get the following error:
```python
  File ".virtualenv/oemof_cosmos/lib/python3.5/site-packages/pyomo/core/base/block.py", line 1314, in component_data_objects sort=sort):
  File ".virtualenv/oemof_cosmos/lib/python3.5/site-packages/pyomo/core/base/block.py", line 1244, in _component_data_iter _items = sorted(_items, key=itemgetter(0))
  File "oemof/oemof/network.py", line 228, in __lt__
    return self.label < other.label
```

### CODE REVIEW

**Comment by henhuy** [comment]
I suggest a very simple solution:
Comparison of the str-representation of labels, instead of labels themselves...
More complex comparisons are possible, but I would avoid over-engineering it!

**Comment by uvchik** [comment]
Sounds reasonable. 

@gnn Do you agree with this solution?

**Comment by henhuy** [comment]
Added try-except AttributeError-Block to avoid error, if `other` is not a `Node` and therefor has no attribute `label` (this can happen when pandas indices, containing mixed indices of `Node` and `str` are sorted).

**Comment by gnn** [comment]
> I suggest a very simple solution:
> Comparison of the str-representation of labels, instead of labels themselves...
> More complex comparisons are possible, but I would avoid over-engineering it!

That's the solution I would've been going for too, so it gets a :+1: from me. The only thing is, that it can be simplified a bit. I pushed the respective changes and explained it in the commit message.
Now you guys can have a look and if you're OK with it, it's good to get merged.

**Comment by henhuy** [comment]
Simple and nice! Thank you!

**Comment by uvchik** [comment]
:+1:  You can squash and merge or simply merge 

We do not have a merge-strategy so far, but we could think about to have one in the future. Feel free to add an issue or a topic for the developer meeting.

**Pull request merged**
