### PR TITLE
Fix #341

### LINKED ISSUE #341: Remove automatic registration of `Node`s
Right now, instantiated `Node`s are automatically added to the most recently instantiated `EnergySystem`. This should be changed. In v0.2.0, new `Node`s should by default not implicitly be added to any `EnergySystem`, but it should be somehow made explicit to which `EnergySystem` a new `Node` should be added, either by:

  * explicitly modifying `Node.registry`,
  * having a parameter on `Node` or
  * manually adding `Node`s to the `EnergySystem`.

### PR DESCRIPTION
**Pull request by gnn**
I made all the necessary changes to disable automatic registration, while still enabling people to switch it on explicitly, if they so desire. I also fixed the tests to work with it and you can now add multiple nodes to an energy system.

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
> Thanks a lot. I really like the way you changed this issue. I think we should change the examples to the more explicit way but even though I like the fast workaround for people who just wants to keep their script running:
> 
> from oemof import network
> from oemof import solph
> es = solph.EnergySystem(timeindex=datetime_index)
> network.Node.registry = es
> For me feel free to merge. I will warn people I know working on the dev branch.
> 
> Thank you

Thanks also from my side. This makes things more explicit although I am one of those people who have to be warned since I am on the dev-Branch ;-)

:+1:

**Comment by uvchik** [comment]
As this is last API changing issue for v0.2. we should merge soon.

**Comment by ckaldemeyer** [comment]
I think it is important to add this feature to WHATSNEW for v.0.2 as all old models will break. Is it enough to provide the examples?

**Comment by nesnoj** [comment]
It was already [added](http://oemof.readthedocs.io/en/latest/whats_new.html#v0-2-0).
But it is currently missing in the rest of the docs ([example](http://oemof.readthedocs.io/en/latest/oemof_solph.html)).

And: It might be helpful if you added something like an ATTENTION sign..

**Comment by uvchik** [comment]
> It was already added.
> But it is currently missing in some/many parts of the docs (example).
> 
> And: It might be helpful if you added something like an ATTENTION sign..

By now these changes are only available in the developer version. This is not a stable version. Using the developer version you should keep an eye on the developing process to be not surprised by unwanted changes.

It is planed to make a list of all API changes compared to v0.1.x until the official release. Furthermore the documentation is pretty much on the state of v0.1.4 so there is still some work to do. If you want to help, please let me know.

**Comment by nesnoj** [comment]
> By now these changes are only available in the developer version. This is not a stable version. Using the developer version you should keep an eye on the developing process to be not surprised by unwanted changes.

Yes, I'm aware of that and I expected you'll merge it..

> It is planed to make a list of all API changes compared to v0.1.x until the official release. Furthermore the documentation is pretty much on the state of v0.1.4 so there is still some work to do. If you want to help, please let me know.

I did not intend to bitch about your great docs, it was just a short note..

**Comment by ckaldemeyer** [comment]
Thanks to both of you for clarification. We'll sort it all out during the "docs-refactoring" I guess ;-)

**Comment by uvchik** [comment]
Sorry, I do not meant to be rude even though my comment sounded a bit annoyed.

I will check the documentation on Monday and make a list. Hopefully we can finish most of it during the developer days. If not I really appreciate some help.

**Pull request merged**
