### PR TITLE
Add method to slice a balance around a bus

### PR DESCRIPTION
**Pull request by ckaldemeyer**
I have added a method to slice inputs/outputs/other around busses as is seems to be a common subset to be extracted from the RDF.

TODOs:

* Update WHATSNEW
* Check docstrings

Could you check and give some feedback?

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
I have missed that sometimes "other" does not exist.

The best would be to only use existing levels of "type":

    results.index.levels[1]
    Out[81]: Index(['from_bus', 'to_bus'], dtype='object', name='type')

I'll have a look how this could be solved..

**Comment by ckaldemeyer** [comment]
It should work with the last commit. Would it be o.k. for you?

Then I would add it to whatsnew

**Comment by uvchik** [comment]
What is `kwargs` for? As I understand it we have one parameter and it is not optional!

```diff
- def slice_bus_balance(self, **kwargs):
+ def slice_bus_balance(self, bus_label):
```

**Comment by ckaldemeyer** [comment]
> What is kwargs for? As I understand it we have one parameter and it is not optional!
> 
> - def slice_bus_balance(self, **kwargs):
> + def slice_bus_balance(self, bus_label):

You're right. I'll kick it out

**Comment by ckaldemeyer** [comment]
Is this fine for you now? I could merge it then

**Comment by uvchik** [comment]
I didn't test it but I trust you that you did. Go ahead.

**Pull request merged**
