### PR TITLE
change licence into REUSE format

### PR DESCRIPTION
**Pull request by uvchik**
According to #406 I changed the license file with find/replace. This leads to the same copyright in every file but that's all I will do to end this annoying topic.

Feel free to change it for individual files (add your name or remove a name), but remove names with care.

```python
"""
This module is about something....

Copyright (c) 2014-2018 Cord Kaldemeyer, Simon Hilpert, Stefan Günther,
                        Uwe Krien

SPDX-License-Identifier: GPL-3.0-or-later
"""
```

### CODE REVIEW

**Comment by uvchik** [comment]
Okay I read the reuse text again and found something that exactly meets our needs. The following paragraph comes from (https://reuse.software/practices/2.0/).


> For a project using the version control system to convey information about copyright, you must:
> 
> - make sure the version control system is publicly accessible and take steps1 to ensure it will remain so, 
> - provide a link back to the original file in version control from each header,
> - ensure that if someone copies the source repository without version control system metadata (such as if they make a tar-file of it), then the version control system metadata relevant for determining copyright must still be included, for example in the form of a bill of materials (see later), an automatically generated log file or similar,
> - make sure the commit metadata reflect the actual copyright (this is particularly important if a project accepts code contributed through mailing lists, bug trackers, or similar, where the original copyright holder is not the one pushing code to version control, or where the copyright is held by an organisation rather than the author.)
> 
> An appropriate header in this case would be:
```
 /*
  * This file is part of project X. It's copyrighted by the contributors
  * recorded in the version control history of the file, available from
  * its original location http://git.example.com/X/filename.c
  * 
  * SPDX-License-Identifier: GPL-3.0
  */
```

 In our case e.g. for the graph.py module this would be:

```python
"""
Some module text.....

This file is part of project oemof. It's copyrighted by the contributors
recorded in the version control history of the file, available from
its original location https://github.com/oemof/oemof/graph.py

SPDX-License-Identifier: GPL-3.0
""""

**Comment by uvchik** [comment]
> Some module text..... This file is part of project oemof. It's copyrighted by the contributors recorded in the version control history of the file, available from its original location https://github.com/oemof/oemof/graph.py SPDX-License-Identifier: GPL-3.0

I adapted the files to the text above.

I added the main authors as reviewers. If they agree I will merge this branch to avoid more merge conflicts as necessary in the future.

**Comment by uvchik** [comment]
I did not add the license for the documentation. I think this is something else for somebody else.

@Ludee What you create a PR for the documentation?

**Comment by Ludee** [comment]
> @Ludee What you create a PR for the documentation?

I can change the Wiki template in https://github.com/oemof/oemof/wiki/Header-and-License

Or do you mean an open license on the documentation readthedocs?

**Comment by uvchik** [comment]
Okay, I talked to @Ludee. and we decided to change the copyright of the documentation from `2014 oemof-team' to `2014-2018 oemof-developer-group` just to make it right.

Then we will start a new PR to change it to a different license such as [creative commons](https://creativecommons.org/).

I would prefer a simple "by" license but other developer may think different.

**Comment by Ludee** [comment]
The generated url to the files are not working. They need the `blob/master/` part as well.
When putting long url names (long filename in folder) PEP8 is complaining.

**Comment by uvchik** [comment]
1. PEP8 allows long URLs.

2. If we use the blob we have to change it for every branch which is kind of annoying. What we can do is to provide a basic link `github.com/oemof/oemof` and the relative link `oemof/oemof/solph/network.py` which is shown on top of the site within github.

```
This file is part of project oemof (github.com/oemof/oemof). It's copyrighted by the 
contributors recorded in the version control history of the file, available from its
original location oemof/oemof/solph/network.py

SPDX-License-Identifier: GPL-3.0-or-later
```

oeli

This is valid for every branch!

**Pull request merged**
