### PR TITLE
Fix issue 190

### PR DESCRIPTION
**Pull request by uvchik**
The name of the keyword is not important to me so change it if you want.

I renamed the keyword of the results DataFrame from `input` to `tobus` and from `output` to `frombus` to make it a bit more intuitive. See #190 for more details.

**Before:**

```python
input_into_pp_gas = myresults.slice_by(obj_label='pp_gas', type='output')
output_from_pp_gas = myresults.slice_by(obj_label='pp_gas', type='input')
```

**Now:**

```python
input_into_pp_gas = myresults.slice_by(obj_label='pp_gas', type='frombus')
output_from_pp_gas = myresults.slice_by(obj_label='pp_gas', type='tobus')
```

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
Thanks for your changes. One small proposal: what to you think about changing it to "to_bus" and "from_bus". I would prefer that since "tobus"/"frombus" might be confusing.

I'll change it if you're o.k. with it

**Comment by uvchik** [comment]
> I'll change it if you're o.k. with it

:+1:

**Comment by uvchik** [comment]
Just did the "find and replace".

**Comment by ckaldemeyer** [comment]
Thanks

**Pull request merged**
