### PR TITLE
Remove index levels from column index

### PR DESCRIPTION
**Pull request by ckaldemeyer**
This is only a one-liner that removes the levels from the column index when using the newly introduced bus balance slice and should be mergeable directly.

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
We could also integrate it into the current release..

**Comment by uvchik** [comment]
If it is tested you can merge it into dev and I will integrate it into the release.

**Comment by ckaldemeyer** [comment]
> If it is tested you can merge it into dev and I will integrate it into the release.

Should be fine as it only affects the labels..

**Comment by ckaldemeyer** [comment]
Thanks!

**Pull request merged**
