### PR TITLE
Feature/#69 docs of oemof

### LINKED ISSUE #69: [docs] Documentation of the new oemof/oemof
This issue hosts the discussion of the new documenation of the oemof/oemof package. Let us use this place to collect comments and concrete ideas for the documentation. See the latest build here: https://oemof.readthedocs.io/en/latest/

### PR DESCRIPTION
**Pull request by gplssm**
Fix #69 

See the updated documentation [here](https://oemof--81.org.readthedocs.build/en/81/)

### What was changed

- Reduced overview for oemof based on existing documentation
- Updated outdated information
- Added the oemof logo to the documentation
- tabular package overview
- General aspects of contributing to oemof libraries
- full-width page

### Points for discussion

- Re-add figure _files/framework_concept.svg? I've kicked it out and simply pointed to www.oemof.org (project, models, publications) and to the list of packages
- Shall we Include timeline figure?
- Taken from existing text, RLI and ZNES are named  as founders of oemof. Do want to keep this or do we want to remove institution names from the docs?

Everyone in addition to the assigned reviewer @uvchik is welcome to discuss this PR!

### CODE REVIEW

**Comment by uvchik** [comment]
Thank you for your effort. I really like the table with the packages :+1: 

 But I would copy the existing text into the new chapters. I think it is easier to build the new text on old fragments than writing a new one.

"about oemof" to "Open Energy Modelling Framework (oemof)"
"Developing oemof" and "Contributing" to "Contributing"

What's your opinion on that?

**Comment by gplssm** [comment]
> Thank you for your effort. I really like the table with the packages +1
> 
> But I would copy the existing text into the new chapters. I think it is easier to build the new text on old fragments than writing a new one.
> 
> "about oemof" to "Open Energy Modelling Framework (oemof)"
> "Developing oemof" and "Contributing" to "Contributing"
> 
> What's your opinion on that?

Thanks for pointing this out again!
In general, I agree with you. Don't re-invent the wheel... But, the text is partiallly outdated, belonging to oemof-solph, too specific while information is already available elsewhere. Therefore, I go the extra step and create new text based on the existing as decribed in https://github.com/oemof/oemof/issues/69#issuecomment-695925822

**Comment by gplssm** [comment]
Hey @uvchik, can I ask you for a quick review of the updated docs. I think it's quite a valuable improvement compared to the outdated docs that are shown at the moment.

**Review by uvchik — APPROVED** [review]
Sorry, I missed this issue due to notification problems.

**Pull request merged**
