### PR TITLE
Features/add min max runtimes

### PR DESCRIPTION
**Pull request by ckaldemeyer**
This adds the possibility to add min and max runtimes for `solph.NonConvexFlows`.

See https://github.com/oemof/oemof_examples/pull/16 for two example usages!

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
Memo:

* Write test
* Remove if statements `if m.flows[i, o].nonconvex.minimum_downtime is not None` from rules

**Comment by ckaldemeyer** [comment]
> Memo:
> 
>     Write test
>     Remove if statements if m.flows[i, o].nonconvex.minimum_downtime is not None from rules

I'll do this when I have time and assign you again!

**Comment by ckaldemeyer** [comment]
> @uvchik
> add constraint test

Looks good!

**Comment by ckaldemeyer** [comment]
I would like to have this in the next release so could you also review @simnh and @jnnr ?

**Comment by ckaldemeyer** [comment]
> I would like to have this in the next release so could you also review @simnh and @jnnr ?

You could also review the examples as they illustrate the functionality: https://github.com/oemof/oemof_examples/pull/16

**Comment by jnnr** [comment]
Good feature! I reviewed the examples, see PR #16. The actual code seems to have a problem passing the tests. There is an error in constraint_tests.py in test_emission_constraints().

**Comment by ckaldemeyer** [comment]
> The actual code seems to have a problem passing the tests. There is an error in constraint_tests.py in test_emission_constraints().

This is weird. The tests have passed with https://github.com/oemof/oemof/pull/446/commits/1795b1df6956cb1d261b5db34667b66dc82b42e9 and started to fail with https://github.com/oemof/oemof/pull/446/commits/f2dfb12ae57da946ba693036694973261aa852ee although the changes only affected the documentation. And the emission constraints are not related to the runtimes..

**Comment by simnh** [comment]
I can not review the correctness of this new functionality atm, Source code looks fine. Only thing was the update of docstrings (I pushed it).

**Comment by uvchik** [comment]
This is a pyomo issue. It comes with 5.4.x. Just add pyomo<5.4 to the setup.py.

Then we should open a new issue to find out if it is a bug or an API change.

**Comment by uvchik** [comment]
See #448.

**Comment by ckaldemeyer** [comment]
> This is a pyomo issue. It comes with 5.4.x. Just add pyomo<5.4 to the setup.py.
> 
> Then we should open a new issue to find out if it is a bug or an API change.

Thanks for pointing this out. Nevertheless, this PR should be mergeable now as @simnh @jnnr and you are fine with it and the Pyomo error is of general nature. @jnnr : Feel free to merge if you are o.k. with my changes!

**Comment by uvchik** [comment]
Okay, I limited the pyomo version to pyomo < 5.4 until we know what happened there.

**Comment by jnnr** [comment]
Very good. Thanks!

**Pull request merged**
