### PR TITLE
Revise/nx graph

### PR DESCRIPTION
**Pull request by uvchik**
**Revision of the graph module**

* I could not see the advantage of using a solph model instead of the energy system as the solph model gets its information from the energy system. That's why I removed the option to pass a model instead of an energy system.
* I added a label to the nodes which helps to show the description in external tools
* I added the weight to edges if an energy system is passed
* I added the option to write the graph to disc as an `.graphml` file.

**Things we may want to discuss**

* Do you like the integrated "write" option or do want to leave it to the user?
* At them moment no "weight" attribute is written if the weight is None. We also could add an empty attribute. I think both ways have advantages.

### CODE REVIEW

**Comment by uvchik** [comment]
Here are the Travis results: https://travis-ci.org/oemof/oemof/builds/330299021

**Comment by jnnr** [comment]
Looks good and gives nice results. Thanks! I like the labeling and weights. The integrated write function can be useful sometimes. If not needed, one just does not pass a filename, so that's perfectly ok.

**Comment by uvchik** [comment]
> The docstring could be revised. Under "Parameters", "filename" appears twice. Should I fix it?

Are you sure you have the latest commit?

**Comment by jnnr** [comment]
Somehow I didn't. Strange. But now its ok.

**Pull request merged**
