### PR TITLE
Fix `electrictal_demand` docstring

### PR DESCRIPTION
**Pull request by gnn**

### CODE REVIEW

**Comment by gnn** [comment]
The docstring for the class lead to a number of sphinx errors. @caro-rli would be kindly have a look at whether my changes preserve the meaning you originally intended? If that's the case you can go ahead and merge the pull request.

**Comment by gnn** [comment]
I've enabled documentation building for this branch on readthedocs, so you can check out whether the [documentation](http://oemof.readthedocs.org/en/features-fix-electrictal_demand-docstring/api/oemof.demandlib.html) looks the way you want it too.

**Comment by caro-rli** [comment]
Thanks a lot! This looks great!

**Comment by caro-rli** [comment]
I merged it back into dev. Didn't know that I can do that directly via github. Thus, I already did a local merge (and now I want to push). Hope this does not lead to any problems.

**Comment by gnn** [comment]
It shouldn't. Best scenario would be that GH figures out that the merge already happened. Worst case would be that we just close this PR. So I'd say go ahead and push the merge. I want to see what happens too.

**Comment by caro-rli** [comment]
Done. It seems that GH figured it out directly. Cool :smiley:

**Pull request merged**
