### PR TITLE
Unpacking of results nodes-tuple #387

### PR DESCRIPTION
**Pull request by henhuy**
Is related to #387 

I adapted `processing.results` function in order to return `(node, None)`-tuples as keys in case of single node result.
This change led to an error in `views.node` function:
"`AttributeError: 'NoneType' object has no attribute 'label'`"
as the `sort_index` function does not work with `None` as comparison, due to `Nodes` internal implementation of the `__lt__` function. 
Therefore, I commented the `sort_index` line out.

Everyone okay with that, or is the sorted index crucial for any implementation?

### CODE REVIEW

**Comment by henhuy** [comment]
okay - unfortunately the tests are using fixed sorted index!
I will change the tests one more time to dynamically get results...

**Comment by ckaldemeyer** [comment]
> Is related to #387
> 
> I adapted processing.results function in order to return (node, None)-tuples as keys in case of single node result.
> This change led to an error in views.node function:
> "AttributeError: 'NoneType' object has no attribute 'label'"
> as the sort_index function does not work with None as comparison, due to Nodes internal implementation of the __lt__ function.
> Therefore, I commented the sort_index line out.

Let's just fix the _lt_ solution in the `Node` class! Sorting is needed and we can then leave the tests as they are. @gnn Would this be a problem?

**Comment by henhuy** [comment]
Okay - I can do this as well once @gnn approved your suggestion.
I would easily check if attribute `label` exists and otherwise set None to be "smaller" than any existing label?!

**Comment by gnn** [comment]
Approved. Except:  please don't check whether the `label` attribute exists, but explicitly check for `None`, if possible. If that's not possible, check for the `label` attribute.
Reason: there might be other objects with a `label` attribute that we really don't want to be able to be compared to `Node`s, as we don't have any idea whether the `label` attribute means the same for the other objects as for `Node`s. So only enabling comparison with `None` is just a precaution to still error out early instead of hiding weird buggy corner cases. But as these might not ever occur, getting this working has higher priority, so if the cautious solution isn't possible, so be it.

Slightly nitpicky remark: a better commit message for the first commit would've been something along the lines of

  >  Change `processing.results`' keys to always be pairs
  >
  > Done by inserting `None` as the second component, i.e. the target, of every key which doesn't have one.
  > Fixes #387.

Reasons:

  * First line shorter than 50 characters and properly capitalized.
  * First line immediately conveys what's happening, rest of the messages explains why it's happening.
  * Relation to #387 is stored in the commit message. Ideally there would be a regression test for the issue, explaining the wrong, desired and final behaviour, which can then easily be related to the commit.
  * #387 will automatically be closed upon merging into `dev`.

But this really is just nitpicking for the future. ;) The new code is awesome and changing the ordering of `Node`s to include comparison with `None` is the obvious and straightforward solution.

**Comment by gnn** [comment]
@henhuy: wanted to try something out, so already made the changes. Look at the PR in your fork, check out the changes and merge or amend them as you see fit.

**Pull request merged**
