### PR TITLE
Added download links for the documentation

### PR DESCRIPTION
**Pull request by stianchris**
As the file for the documentation is a bit hidden, I included the links and a little description on how to find other versions.

### CODE REVIEW

**Comment by uvchik** [comment]
Couldn't we just add one line:

Go to the [download page](http://readthedocs.org/projects/oemof/downloads/) to download different versions and formats (pdf, html, epup) of the documentation.

**Comment by stianchris** [comment]
Yes, better. Thanks!

**Comment by uvchik** [comment]
Now it looks like this: https://github.com/oemof/oemof/tree/docs/how_to_cite_oemof

If it is okay for you, you can close this issue. I will merge the other one soon.

Thank you for your contribution :smile:

**Comment by ckaldemeyer** [comment]
Oh, I did not see that @uvchik's proposal (https://github.com/oemof/oemof/pull/316) was an alternative to yours :-) I'd rather go with his one if that's o.k. Thanks anyway!

**Comment by uvchik** [comment]
@stianchris, please close this issue if you are fine with the changes or add a comment in reply to [this](https://github.com/oemof/oemof/pull/314#issuecomment-301901884).

**Comment by stianchris** [comment]
I'm fine with it!

**Pull request closed without merging**
