### PR TITLE
Features/put result dict and df into package

### PR DESCRIPTION
**Pull request by ckaldemeyer**
This only holds the first changes of the big dataframe refactoring (https://github.com/oemof/oemof/pull/297) which put the result-dict and -df into single modules in the outputlib package.

The merge conflicts with https://github.com/oemof/oemof/pull/296 should be fixed and tests are running well.

@uvchik : Where did you keep the notes about how to test properly after the problems with the last release? I don't remember it anymore but know you kept it somewhere..

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
I have added an ordered column list for the `slice_unstacked() (if formatted=True)` and thus also `slice_bus_balance()` method per default.

Normally the dataframe returns the columns in some order e. g. `['pp_oil', 'demand_el', 'pp_biogas']` and now it's `['demand_el', 'pp_biogas', 'pp_oil']`. This is also used when results are written to CSVs using `bus_balance_to_csv()` and should improve the usability for Excel folks, etc.

**Comment by ckaldemeyer** [comment]
Is this o.k. now?

**Comment by uvchik** [comment]
My examples do not work any more.

```python
  File ".../oemof/oemof/solph/models.py", line 15, in <module>
    from ..outputlib import result_dict
ImportError: cannot import name 'result_dict' 
```

**Comment by uvchik** [comment]
I'm confused now. What is the oemof results API? DataFrame or Dictionary?

If it is the Dictionary, the creation of the dictionary belongs to solph. Though the creation of the DataFrame should work for future packages next to solph. Therefore the creation of the DataFrame is on the oemof-level.

If the DataFrame is the results API, the creation of the DataFrame still belongs to the solph package.

**Comment by ckaldemeyer** [comment]
> My examples do not work any more.
> 
>   File ".../oemof/oemof/solph/models.py", line 15, in <module>
>     from ..outputlib import result_dict
> ImportError: cannot import name 'result_dict'

Which one?

If I use the test only the two known errors pop up:

```
cord@cord-Laptop:~/Programmierung/oemof/examples$ py3 oemof_full_check.py 
Check Storage invest example...
Check Simple least costs optimization...
Check Flexible Modelling...
Check Dispatch model with csv reader...
Check Investment model with csv reader...
Check Variable CHP example...
...
----------------------------------------------------------------------
Ran 42 tests in 0.341s

FAILED (failures=2)
Some nosetests failed.See the output above for more information!
Some example tests failed.See the output above for more information!
```

**Comment by ckaldemeyer** [comment]
> I'm confused now. What is the oemof results API? DataFrame or Dictionary?
> 
> If it is the Dictionary, the creation of the dictionary belongs to solph. Though the creation of the DataFrame should work for future packages next to solph. Therefore the creation of the DataFrame is on the oemof-level.
> 
> If the DataFrame is the results API, the creation of the DataFrame still belongs to the solph package.

I am not sure myself here but for me both, the dict and the dataframe are already quite solph-specific even if they have been placed on the core layer. Thus, I treated them in the same way.

But maybe a webco as you proposed would be good here!

**Comment by uvchik** [comment]
I use commit 87f4991dfa. May you have files/changes that you did not push?
I will try it on a different system. Could you try it on a clean environment?

> Some example tests failed.See the output above for more information!

What are these errors. I do not know about known errors.

**Comment by ckaldemeyer** [comment]
> I use commit 87f4991. May you have files/changes that you did not push?
> I will try it on a different system. Could you try it on a clean environment?

I have no unpushed files and I am on the latest commit:

```
cord@cord-Laptop:~/Programmierung/oemof/examples$ git status
Auf Branch features/put-result-dict-and-df-into-package
Ihr Branch ist auf dem selben Stand wie 'origin/features/put-result-dict-and-df-into-package'.
cord@cord-Laptop:~/Programmierung/oemof/examples$ git pull
Already up-to-date.
```

> What are these errors. I do not know about known errors.

The ones that occured with the newer Pyomo version:

```
....................FF....................
======================================================================
FAIL: Wrong constraints for fixed source + invest sink w. `summed_max`.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cord/.anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 149, in test_fixed_source_invest_sink
    self.compare_lp_files('fixed_source_invest_sink.lp')
  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 72, in compare_lp_files
    lineterm="")))
AssertionError: Failed matching expected with generated lp file:
--- tests/lp_files/fixed_source_invest_sink.lp
+++ fixed_source_invest_sink_tmp.lp
@@ -11,16 +11,16 @@
 s.t.
 
 c_e_Bus_balance(electricityBus_0)_:
--1 flow(electricityBus_excess_0)
-= -12000000
++1 flow(electricityBus_excess_0)
+= 12000000
 
 c_e_Bus_balance(electricityBus_1)_:
--1 flow(electricityBus_excess_1)
-= -16000000
++1 flow(electricityBus_excess_1)
+= 16000000
 
 c_e_Bus_balance(electricityBus_2)_:
--1 flow(electricityBus_excess_2)
-= -14000000
++1 flow(electricityBus_excess_2)
+= 14000000
 
 c_u_InvestmentFlow_max(electricityBus_excess_0)_:
 -0.80000000000000004 InvestmentFlow_invest(electricityBus_excess)

======================================================================
FAIL: Constraint test with a fixed source and a variable sink.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cord/.anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 133, in test_fixed_source_variable_sink
    self.compare_lp_files('fixed_source_variable_sink.lp')
  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 72, in compare_lp_files
    lineterm="")))
AssertionError: Failed matching expected with generated lp file:
--- tests/lp_files/fixed_source_variable_sink.lp
+++ fixed_source_variable_sink_tmp.lp
@@ -10,16 +10,16 @@
 s.t.
 
 c_e_Bus_balance(electricityBus_0)_:
--1 flow(electricityBus_excess_0)
-= -430000
++1 flow(electricityBus_excess_0)
+= 430000
 
 c_e_Bus_balance(electricityBus_1)_:
--1 flow(electricityBus_excess_1)
-= -720000
++1 flow(electricityBus_excess_1)
+= 720000
 
 c_e_Bus_balance(electricityBus_2)_:
--1 flow(electricityBus_excess_2)
-= -290000
++1 flow(electricityBus_excess_2)
+= 290000
 
 c_e_ONE_VAR_CONSTANT:
 ONE_VAR_CONSTANT = 1.0

```

**Comment by uvchik** [comment]
> The ones that occured with the newer Pyomo version:

Sorry, I missed that.

You posted  the output of the nosetest but what is the output of the example tests?

**Comment by ckaldemeyer** [comment]
> The ones that occured with the newer Pyomo version:
> Sorry, I missed that.
> 
> You posted the output of the nosetest but what is the output of the example tests?

Oh, I also get an error ;-) :

```
cord@cord-Laptop:~/Programmierung/oemof/examples$ py3 examples.py 
Traceback (most recent call last):
  File "examples.py", line 1, in <module>
    from .solph.csv_reader.investment.investment import run_investment_example
SystemError: Parent module '' not loaded, cannot perform relative import

```

But before I start fixing, etc. we might talk about the results API and how we want it straight, or not? Otherwise it might be effort for nothing.

**Comment by uvchik** [comment]
> Oh, I also get an error ;-) :

No, this is another error. You cannot call example.py within the package. Try one of the examples or use oemof_full test to see which examples fail.

**Comment by uvchik** [comment]
Get the same error on a different computer.

```python
Traceback (most recent call last):
  File "/git_local/oemof/examples/solph/storage_investment/storage_investment.py", line 35, in <module>
    from oemof import outputlib
  File "/git_local/oemof/oemof/outputlib/__init__.py", line 1, in <module>
    from .result_dict import result_dict
  File "/git_local/oemof/oemof/outputlib/result_dict.py", line 3, in <module>
    from ..solph.network import Storage
  File "/git_local/oemof/oemof/solph/__init__.py", line 9, in <module>
    from oemof.solph.models import OperationalModel
  File "/git_local/oemof/oemof/solph/models.py", line 15, in <module>
    from ..outputlib import result_dict
ImportError: cannot import name 'result_dict'
```

**Comment by ckaldemeyer** [comment]
> Get the same error on a different computer.
> 
> Traceback (most recent call last):
>   File "/git_local/oemof/examples/solph/storage_investment/storage_investment.py", line 35, in <module>
>     from oemof import outputlib
>   File "/git_local/oemof/oemof/outputlib/__init__.py", line 1, in <module>
>     from .result_dict import result_dict
>   File "/git_local/oemof/oemof/outputlib/result_dict.py", line 3, in <module>
>     from ..solph.network import Storage
>   File "/git_local/oemof/oemof/solph/__init__.py", line 9, in <module>
>     from oemof.solph.models import OperationalModel
>   File "/git_local/oemof/oemof/solph/models.py", line 15, in <module>
>     from ..outputlib import result_dict
> ImportError: cannot import name 'result_dict'

Yep, I see. I'll have a look when I find the time..

**Comment by simnh** [comment]
Couple of reminders/question to-dos: 

* Should we rename the modules to "results_to_x" instead of "results_x" ? (Like I did for components?)

* [ ] Write to components needs to be checked for correct 
* [ ] We should a check in the OperationModel, if the problem is infeasible, right now there only comes an error when writing results, that not exist. ( see: #292 ) 
* [ ] Write checks inside the modules, if results actually exist (I called on a not-solve instance-> throw error.

**Comment by ckaldemeyer** [comment]
@uvchik : You can ignore the merge conflict as I will take care of it later.

The thing I don't understand is that nosetests fail:

	cord@cord-Laptop:~/Programmierung/oemof/examples$ py3 oemof_full_check.py 
	Check Storage invest example...
	Check Simple least costs optimization...
	Check Flexible Modelling...
	Check Dispatch model with csv reader...
	Check Investment model with csv reader...
	Check Variable CHP example...
	16:58:38-INFO-Path for logging: /home/cord/.oemof/log_files
	16:58:38-INFO-Used oemof version: c8375664@features/put-result-dict-and-df-into-package
	16:58:38-INFO-*********************************************
	16:58:38-INFO-Simple least costs optimization
	16:58:38-INFO-Used solver: cbc
	16:58:38-INFO-Run check: Failed
	16:58:38-INFO-Result check: Failed
	16:58:38-ERROR-'module' object is not callable
	16:58:38-INFO-*********************************************
	16:58:38-INFO-Storage invest example
	16:58:38-INFO-Used solver: cbc
	16:58:38-INFO-Run check: Failed
	16:58:38-INFO-Result check: Failed
	16:58:38-ERROR-'module' object is not callable
	16:58:38-INFO-*********************************************
	16:58:38-INFO-Variable CHP example
	16:58:38-INFO-Used solver: cbc
	16:58:38-INFO-Run check: Failed
	16:58:38-INFO-Result check: Failed
	16:58:38-ERROR-'module' object is not callable
	16:58:38-INFO-*********************************************
	16:58:38-INFO-Flexible Modelling
	16:58:38-INFO-Used solver: cbc
	16:58:38-INFO-Run check: Failed
	16:58:38-INFO-Result check: Failed
	16:58:38-ERROR-'module' object is not callable
	16:58:38-INFO-*********************************************
	16:58:38-INFO-Investment model with csv reader
	16:58:38-INFO-Used solver: cbc
	16:58:38-INFO-Run check: Failed
	16:58:38-INFO-Result check: Failed
	16:58:38-ERROR-'module' object is not callable
	16:58:38-INFO-*********************************************
	16:58:38-INFO-Dispatch model with csv reader
	16:58:38-INFO-Used solver: cbc
	16:58:38-INFO-Run check: Failed
	16:58:38-INFO-Result check: Failed
	16:58:38-ERROR-'module' object is not callable
	..GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
	....................FF....................
	======================================================================
	FAIL: Wrong constraints for fixed source + invest sink w. `summed_max`.
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/cord/.anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
	    self.test(*self.arg)
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 149, in test_fixed_source_invest_sink
	    self.compare_lp_files('fixed_source_invest_sink.lp')
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 72, in compare_lp_files
	    lineterm="")))
	AssertionError: Failed matching expected with generated lp file:
	--- tests/lp_files/fixed_source_invest_sink.lp
	+++ fixed_source_invest_sink_tmp.lp
	@@ -11,16 +11,16 @@
	 s.t.
	 
	 c_e_Bus_balance(electricityBus_0)_:
	--1 flow(electricityBus_excess_0)
	-= -12000000
	++1 flow(electricityBus_excess_0)
	+= 12000000
	 
	 c_e_Bus_balance(electricityBus_1)_:
	--1 flow(electricityBus_excess_1)
	-= -16000000
	++1 flow(electricityBus_excess_1)
	+= 16000000
	 
	 c_e_Bus_balance(electricityBus_2)_:
	--1 flow(electricityBus_excess_2)
	-= -14000000
	++1 flow(electricityBus_excess_2)
	+= 14000000
	 
	 c_u_InvestmentFlow_max(electricityBus_excess_0)_:
	 -0.80000000000000004 InvestmentFlow_invest(electricityBus_excess)

	======================================================================
	FAIL: Constraint test with a fixed source and a variable sink.
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/cord/.anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
	    self.test(*self.arg)
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 133, in test_fixed_source_variable_sink
	    self.compare_lp_files('fixed_source_variable_sink.lp')
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 72, in compare_lp_files
	    lineterm="")))
	AssertionError: Failed matching expected with generated lp file:
	--- tests/lp_files/fixed_source_variable_sink.lp
	+++ fixed_source_variable_sink_tmp.lp
	@@ -10,16 +10,16 @@
	 s.t.
	 
	 c_e_Bus_balance(electricityBus_0)_:
	--1 flow(electricityBus_excess_0)
	-= -430000
	++1 flow(electricityBus_excess_0)
	+= 430000
	 
	 c_e_Bus_balance(electricityBus_1)_:
	--1 flow(electricityBus_excess_1)
	-= -720000
	++1 flow(electricityBus_excess_1)
	+= 720000
	 
	 c_e_Bus_balance(electricityBus_2)_:
	--1 flow(electricityBus_excess_2)
	-= -290000
	++1 flow(electricityBus_excess_2)
	+= 290000
	 
	 c_e_ONE_VAR_CONSTANT:
	 ONE_VAR_CONSTANT = 1.0

	----------------------------------------------------------------------
	Ran 44 tests in 0.486s

	FAILED (failures=2)
	Some nosetests failed.See the output above for more information!
	Some example tests failed.See the output above for more information!

while the examples themselves (if I execute them individually) are running correctly since results are written back (which means that the result dict and dataframe are created).

I hope you have a hint for me here... :-)

**Comment by uvchik** [comment]
For some reason python tries to call the module instead of the function. Both have the same name in your case, so you have to careful with the imports to avoid such errors.

There is another error caused by a8022dc590. In the full check the function expects just one return value, but this is easy to fix.

**Comment by ckaldemeyer** [comment]
> For some reason python tries to call the module instead of the function. Both have the same name in your case, so you have to be careful with the imports to avoid such errors. You can also use different names, but I do not know which way is more pythonic.
> 
> There is another error caused by a8022dc. In the full check the function expects just one return value, but this is easy to fix. Shame on you, this is already part of the dev branch

Thanks. I'll have a look..at both :smile:

**Comment by ckaldemeyer** [comment]
> For some reason python tries to call the module instead of the function. Both have the same name in your case, so you have to be careful with the imports to avoid such errors. You can also use different names, but I do not know which way is more pythonic.

Actually, it is quite obvious from the error message now!

The only thing I don't understand is that single examples are still running:

	cord@cord-Laptop:~/Programmierung/oemof/examples/solph/csv_reader$ py3 dispatch/dispatch.py 
	09:29:54-INFO-Path for logging: /home/cord/.oemof/log_files
	09:29:54-INFO-Used oemof version: c8375664@features/put-result-dict-and-df-into-package
	09:29:54-INFO-Starting optimization
	09:29:57-INFO-Done!
	09:29:57-INFO-The results can be found in /home/cord/csv_dispatch
	09:29:57-INFO-Read the documentation (outputlib) to learn how to process the results.
	09:29:57-INFO-Showing plots
	GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

To me, this means that in some cases it works and in others it doesn't. I'll track it down..

**Comment by uvchik** [comment]
For me all examples failed. We will not care if it works now 😄 

As you fixed the graph-plot example, could you make the following warning more explicit e.g. "graph plots will not work". It is confusing like this because most plots work.

```python
WARNING:root:Networkx could not be imported. Plotting will not work.
```

**Comment by uvchik** [comment]
I do not know if a whatsnew message is necessary but you should add your name to the contributor list.

Feel free to merge from my side.

**Comment by ckaldemeyer** [comment]
> For me all examples failed. We will not care if it works now

This is due to https://github.com/oemof/oemof/commit/4fefc4bb71f36ac6b33d0193180a5fd546bea283 and already on the dev which I have merged to resolve conflicts.

> As you fixed the graph-plot example, could you make the following warning more explicit e.g. "graph plots will not work". It is confusing like this because most plots work.
> 
> WARNING:root:Networkx could not be imported. Plotting will not work.

Yes, I'll create a logging message.

> I do not know if a whatsnew message is necessary but you should add your name to the contributor list.
> 
> Feel free to merge from my side.

:+1:

**Comment by ckaldemeyer** [comment]
Should work now. @simnh can merge if he is fine, too.

**Comment by uvchik** [comment]
> Yes, I'll create a logging message.

There is already a logging message but this message is to general.

https://github.com/oemof/oemof/blob/dev/oemof/outputlib/graph_tools.py

**Comment by ckaldemeyer** [comment]
> Yes, I'll create a logging message.
> There is already a logging message but this message is to general.
> 
> https://github.com/oemof/oemof/blob/dev/oemof/outputlib/graph_tools.py#L11

Go ahead if you have an idea!

**Comment by uvchik** [comment]
I removed it. It is duplicate.

**Comment by ckaldemeyer** [comment]
> I removed it. It is duplicate.

Thanks! Sometimes this form of communication (dicsussion) takes just longer than fixing it personally :smile:

**Comment by simnh** [comment]
yeah i would think there are still things missing, but we can do it later on...probably it will break the API..so for these are tasks for the future

**Comment by ckaldemeyer** [comment]
> yeah i would think there are still things missing, but we can do it later on...probably it will break the API..so for these are tasks for the future

Let's discuss it tomorrow. Thanks!

**Comment by uvchik** [comment]
> Thanks! Sometimes this form of communication (dicsussion) takes just longer than fixing it personally 😄

You are right but it is sometime a thin line between shortening things up and messing in somebody else's code. It is the downside of community projects.

**Pull request merged**
