### PR TITLE
Update developing_oemof.rst

### PR DESCRIPTION
**Pull request by drjod**
das hatte nicht funktioniert

### CODE REVIEW

**Comment by uvchik** [comment]
Both ways should work. You need an ssh-key to use it: https://help.github.com/articles/which-remote-url-should-i-use/

We could just write "Clone the repository" and add a link to the following help page: https://help.github.com/articles/cloning-a-repository/

**Comment by uvchik** [comment]
I can fix this when we revise the documentation at the meeting right before the release.

**Comment by ckaldemeyer** [comment]
> I can fix this when we revise the documentation at the meeting right before the release.

:+1:

**Comment by uvchik** [comment]
Fixed with commit 90a30afaef0369.

**Pull request closed without merging**
