### PR TITLE
Revise param_results/results (e.g. #463)

### PR DESCRIPTION
**Pull request by henhuy**
This PR fixes points 1 & 3 from #463 

 * [x] ~~fix documentation~~
 * [x] None is not String but NoneType after to_string operation
 * [x] ~~Rename parm_results to `parameter_as_dict`~~
 * [x] ~~Add to outputlib documentation~~ -> see #500

Open questions?

 * [x] ~~Should parm_results work with views as well (s. #475, #494)?~~
 * [x] ~~Should the result dictionary rather be an object (s #470)?~~ (nobody is interested by now)

### CODE REVIEW

**Comment by jnnr** [comment]
I just discussed with Uwe about the API of the outputlib, and we would like to ask you about your experience and opinion.

@henhuy @gnn @simnh : In which cases is the results dictionary used in such a way that the keys are really the objects? The cases I've seen always convert to keys_as_strings. The oemof_examples do that. Can you give any examples, i.e. use cases, in which the actual objects are used?

**Comment by uvchik** [comment]
I have two ideas how we could merge the results and param_results into one structure.

`all_results = merge_results(results, param_resutls)`

`all_results = resutls(model, parameter=True)`

**Comment by uvchik** [comment]
> I have two ideas how we could merge the results and param_results into one structure.
> 
> all_results = merge_results(results, param_resutls)
> 
> all_results = results(model, parameter=True)

I changed my mind. Let us merge it.

**Comment by uvchik** [comment]
If nobody objects we can merge.

**Comment by uvchik** [comment]
Sorry, I accidentally closed this PR.

The new work-around does not work with tuples as label.

**Comment by uvchik** [comment]
I changed my mind a little. I am fine with both variants None (none-type) and 'None' (string). It just have to be clear. We could make it optional with something like `keep_none_type=False`. This would leave the API untouched.

**Comment by henhuy** [comment]
> We could make it optional with something like `keep_none_type=False`
I am okay with that solution!
If #508 is accepted we can merge it and then tests should pass...

**Comment by henhuy** [comment]
Added `keep_none_type=False` parameter to `processing.convert_keys_to_string` **and** `views.node` function (as this function uses `processing.convert_keys_to_strings` internally).
Now, this PR waits for acceptation of PR #508 - after that, tests should pass...

**Comment by uvchik** [comment]
Hey, great :-)

I agree to set keep_none_type=False as default, because the default call of `convert_keys_to_string` should convert all(!) keys to strings, that is what people expect.

We have to wait for @gnn to approve #508 but then we can merge both. Thanks again.

**Comment by uvchik** [comment]
I accidentality merged this PR a little too early. 

We just waited for PR #508 which is merged now. 

I check the dev branch after the merge and all tests are fine :-)

Thank you @henhuy for the improvements.

**Pull request merged**
