### PR TITLE
First refactoring/solph/dev

### PR DESCRIPTION
**Pull request by uvchik**
What are the next steps? Use this PR for wishes and to discuss global aspects or create issues for concrete matters.

### CODE REVIEW

**Comment by uvchik** [comment]
Tests work, examples work. Documentation needs support. I will merge it to the release branch.

**Comment by Jazzpilz** [comment]
It looks like the hub.connect() function is broken, in network/__init__.py:
AttributeError: 'WeakKeyDictionary' object has no attribute 'append'

**Comment by Jazzpilz** [comment]
Sorry, I mean oemof.core.energysystem.connect()

**Comment by uvchik** [comment]
You are right. thank you. 

The transport class and the transformer class were the same, so we decided to remove the transport class. To use the invest mode for the transport (in both directions) there might be a transport class in the future. 

Anyhow, the connect method is not needed any more. Use two transformer objects instead.

**Comment by Jazzpilz** [comment]
Ok thank you for the explanation!

**Pull request merged**
