### PR TITLE
Fix/review doc - fix some AE/BE typos

### PR DESCRIPTION
**Pull request by joroeder**
Fix some AE/BE typos in the 'getting_startet' and creating pull request for test purpose

### CODE REVIEW

**Comment by uvchik** [comment]
As we decided to use BE in oemof I thought that optimisation is right. I think even in BE optimization is fine, too, but it seems to be less common in BE.

**Comment by uvchik** [comment]
I just saw that this is already merged. As the 'z'-writing is allowed in BE it might not be worth to revert it but I am still confused.

**Comment by joroeder** [comment]
Oh, sorry. When we saw in the hands-on review docs session on the last dev meeting, that it seemed that both variants were used, we thought, that there was no decision yet. If we want to use BE, we should revert it, I agree.

> As we decided to use BE in oemof
>

Where do we find such decisions? readthedocs or wiki? Actually, to have two places you need to check before doing something, is not very convenient in my opinion. Why don't we put all the stuff from the oemof/oemof wiki in readthedocs?

**Comment by uvchik** [comment]
You are totally right. This should be part of the documentation but it isn't (I thought it is).

There are two sections about developing the documentation which is not good:

- https://oemof.readthedocs.io/en/latest/developing_oemof.html#contribute-to-the-documentation

- https://oemof.readthedocs.io/en/latest/developing_oemof.html#documentation

We should merge them and add the information that we use BE.

The Wiki is only for special or non-static information. For example the "how to release" Wiki is not important for somebody who wants to contribute.

**Pull request merged**
