### PR TITLE
Add examples for SDEWES confernce paper

### PR DESCRIPTION
**Pull request by simnh**
* [ ] Decide on data
* [ ] Add CHP to unit commitment
* [ ] Add emission limit for micro grid investment to show applicability of indiv. constraints?

### CODE REVIEW

**Comment by gplssm** [comment]
You requested a review. Could you please specify a little bit more what I should review? I won't go through these 9k lines of code...

**Comment by simnh** [comment]
sorry wrong person ;)

**Comment by ckaldemeyer** [comment]
> Decide on data
>  Add CHP to unit commitment
>  Add emission limit for micro grid investment to show applicability of indiv. constraints?

Is this ready to review!?

**Comment by simnh** [comment]
mh...kind of, you can have a look...and maybe add a generic chp to the unit_commitment example

**Comment by simnh** [comment]
I have a question: Where do we store the oemof examples now? (I know there was  a discussion, but I could not find it right now)..I would then move the SDEWES examples there also..

**Comment by birgits** [comment]
There is a new repository: https://github.com/oemof/examples

**Comment by uvchik** [comment]
By the way. I would like to rename the example repository. See: https://github.com/oemof/organisation/issues/21.

**Comment by simnh** [comment]
Will be moved to the example repository...

**Pull request closed without merging**
