### PR TITLE
Feature: Integrate oemof logos into docs

### PR DESCRIPTION
**Pull request by fwitte**
Logo to be found in

- README
- About oemof
- readthedocs sidebar header

Also removes the version number in readthedocs (why should this repo still have a version number...?)

### CODE REVIEW

**Comment by fwitte** [comment]
Interestingly, when generating the docs locally, the logo in "about oemof" appears while it does not on readthedocs. The logo in the sidebar appears in both local and online docs, even though the path is basically the same.

Maybe copy the logos into the "_files" folder, too? Is there any solution without redundancy?

**Review by jnnr — COMMENTED** [review]
Thanks for opening this. I like the idea of showing the logos a bit more, at the right place.
* Readme: Very good, this has been missing
* About oemof: I am not sure if this is the best place. Maybe rather put it on top of "contents" or "overview"?
* Talking about "overview", which is the readme rendered in the docs: In that case, the link to the image does not seem to work, at least in my local build.
* Are we sure that the logo is nicely and symmetric? We had a skewed on, and ever since I saw it I am not sure if I can trust my eyes. But maybe that's corrected since long.

**Comment by fwitte** [comment]
>     * Readme: Very good, this has been missing

For future reference (e.g. the https://github.com/oemof/oemof-solph/ repo), the link to the image in the README should be the link to the github file not the local path, if we want it to be rendered correctly on PyPi (https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github).

>     * About oemof: I am not sure if this is the best place. Maybe rather put it on top of "contents" or "overview"?

I changed the landing page for TESPy to not only feature the list of contents. Maybe consider this for the other repos, too. Basically, the landing page (https://tespy.readthedocs.io/en/dev/) shows the same content as the first page of the navigation bar (https://tespy.readthedocs.io/en/dev/introduction.html) an on top of that the contents.

>     * Talking about "overview", which is the readme rendered in the docs: In that case, the link to the image does not seem to work, at least in my local build.

Locally it works for me, readthedocs does not render it. Any idea, on how to fix the link? Must the image be part of the docs folder tree?

>     * Are we sure that the logo is nicely and symmetric? We had a skewed on, and ever since I saw it I am not sure if I can trust my eyes. But maybe that's corrected since long.

Yes, it was replaced about a year ago, I think.

**Comment by uvchik** [comment]
I just updated this PR. The docs are now based on the sketch of @gplssm.

* [README](https://github.com/oemof/oemof/tree/feature/integrate_oemof_logo)
* [READTHEDOCS](https://oemof.readthedocs.io/en/feature-integrate_oemof_logo/index.html)

**Comment by uvchik** [comment]
I tend to remove the headline: Overview: Open Energy Modelling Framework (oemof)

For me it is kind of duplicate the logo.

**Comment by fwitte** [comment]
Thank you for the feedback an merge of the new structure. Looks great!

> I tend to remove the headline: Overview: Open Energy Modelling Framework (oemof)

Keeping "Open Energy Modelling Framework" in the header might be important for search machine indexing. But I am in no way an expert... :D. 

> For me it is kind of duplicate the logo. But I really like the logo at readthedocs.

The logo seems to render on rtd, too, now. Thanks for the fix (?) :).

**Comment by p-snft** [comment]
> I tend to remove the headline: Overview: Open Energy Modelling Framework (oemof)
> 
> For me it is kind of duplicate the logo. But I really like the logo at readthedocs.

In my opinion, there should always be a maschine readable version of the headline.

**Comment by uvchik** [comment]
I agree with both of you. We can leave it as it is.

**Review by uvchik — APPROVED** [review]

**Review by p-snft — APPROVED** [review]
I like.

**Comment by uvchik** [comment]
> We still have the problem that the logo writes modelling with a single "L".

This is a website issue. There is the wrong logo on the website.

**Comment by fwitte** [comment]
Thanks for the feedback everyone!

**Pull request merged**
