### PR TITLE
Features/examples commandline script

### PR DESCRIPTION
**Pull request by gplssm**
Created a script callable from command-line to execute examples after installation via pip3. All this is virtualenv-proof, but not proof in general.

In the end examples are callable by 

```
usage: oemof_examples [-h] example

Choose one of the examples below listed examples!

positional arguments:
  example     Example name (from list of examples)

optional arguments:
  -h, --help  show this help message and exit

        List of examples

         * storage_invest
         * simple_least_costs
         * investment
         * flexible_modelling
```

Issue I had during implementation
- #225 
- #226
- import in files under examples/ because parent package is not imported

We should try to answer #225 until release of v0.1.

### CODE REVIEW

**Comment by simnh** [comment]
Great! As I see it now, should we rename the examples for better 'self - description'? We discussed this somewhere already? Or can we do it later after the release?

**Comment by gplssm** [comment]
I discussed with @uvchik... We decided to keep it as it is, keeping the issue in mind (see #226) and solve this by the next release with a more sophisticated solution.

I resolved merge conflicts and added _operational example_ to examples script.
@uvchik please wait with merge of this PR until we have a final decision on #225

**Comment by gplssm** [comment]
Arrrggg! Tests are failing now. I don't get why...!? Maybe `oemof_full_test.py` now executes _operational_model_ because I added an ___init__.py__ file there...

**Comment by uvchik** [comment]
All seems to work now. Thank you @gplssm for your work :sunflower:

**Pull request merged**
