### PR TITLE
Allow non linear investcosts

### PR DESCRIPTION
**Pull request by simnh**

### CODE REVIEW

**Comment by uvchik** [comment]
Do want to merge this until November 1?

**Comment by simnh** [comment]
Yes why not? This is actually already finished...I like the idea of having some features that are included (if they are not that big and do not affect the normal usage). But I think we do not need to have that extensively documented....

**Comment by simnh** [comment]
we can talk about the naming though, but we already saw that it would be nice to have a module were we can keep stuff that is used by more than one block...

**Comment by uvchik** [comment]
It is fine for me.

> But I think we do not need to have that extensively documented....

Yes, but I think we should document it shortly and write at least one test.

**Comment by simnh** [comment]
ok you are write i guess.

**Comment by simnh** [comment]
Ok, besides test etc. does any one have problems with the internal structure, naming etc. of this feature?

**Pull request closed without merging**
