### PR TITLE
Features/solph speed up

### PR DESCRIPTION
**Pull request by simnh**
This pull request aims to use functionality that has been implemented by the pypsa developers to speed up constraint building etc. We had that for the old version already, I think we should try to use it now as well. For the bus balance for example it is faster, and I think significantly for large instances.  Took me some time to implement it for lineartransformer as well. There it does not speed thins up (it's even slower but maybe it's still not equivalent to the old expression). So from my point of view the procedure would look like this:
- taking major constraints (busbalance, lineartransformer etc) and compare results for a large test instance (maybe renpassis europe model) 
- where we identify enhancement we will use the improved code. 

Right now you can check it out in the blocks.py module (look at the LinearTransformer class there) 

The test fail at the moment, because the lp-files look differently (but this is just due to different signs inside equations.

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
Does this build on the standard API of pyomo or is it some sort of hack? I am just asking because of maintenance reasons and the  usability for new users..

**Comment by simnh** [comment]
this is a hack..so we should probably keep both, the original code and the hack...but it's definitely worth it.

**Comment by simnh** [comment]
I just thought I move the code here, so that anyone can simply start altering and testing faster code.

**Comment by ckaldemeyer** [comment]
> this is a hack..so we should probably keep both, the original code and the hack...but it's definitely worth it.

Sounds good! Especially for memory consuming models or if models are embedded (e.g. in an EA). Thanks

**Comment by simnh** [comment]
Ah for memory consumption @gnn  will probably add another hack (at least i hope so), also from pypsa....i'll be great!

**Comment by uvchik** [comment]
> i'll be great! 

You definitely will :smirk: 

By now you just replaced the code (I guess for testing purpose). Do you have an idea how to organise both ways next to each other. Shouldn't we add something like `fast_blocks`.... I think plumbing is not a good place for a special feature.

**Comment by simnh** [comment]
I talked to Tom B. and Gabriel H from the pyomo developers. The developers actually recommen doing it this way (like in PyPSA) to speed things up...So maybe we should do this ? The implementation is basically ready. Only the lp-files inside tests have to be updated...

**Comment by ckaldemeyer** [comment]
> I talked to Tom B. and Gabriel H from the pyomo developers. The developers actually recommen doing it this way (like in PyPSA) to speed things up...So maybe we should do this ? The implementation is basically ready. Only the lp-files inside tests have to be updated...

Based on this, for me, this is more like a "Must Do" because it affects every model and only requires some time.

But can it break in certain cases when the API changes, etc..?! If not, I would implement it.

**Comment by simnh** [comment]
Ok, I guess API won't be a problem so far...But of course I can not guarantee it...(however we have requirements and use 'fancy' pyomo stuff everywhere...thus I think this is not an argument for me...

**Comment by uvchik** [comment]
The LP-files are not the problem, because I guess it is just the order.

If it is faster, we should give it a try. (Do we know how much faster?)

We have to keep an eye on the pyomo updates. In urgent case we can just change the version number in the dependencies. We (developer) should try to keep pyomo up to date, that we become aware of problems.

**Comment by simnh** [comment]
There are some new discussions going on. I will open an issue where we can discuss these things. these implementations will be obsolete.

**Pull request closed without merging**
