### PR TITLE
Add LinearM1Transformer to solph module

### PR DESCRIPTION
**Pull request by simnh**
This pull request adds a M:1 Transformer and is connected to #281 . 

We need a new name maybe? I tested the code, but I did not push an example for now because I do not have the time...You can simply add a Transformer like this somewhere

```
    LinearM1Transformer(label='LM1',
                        outputs={b_el: Flow()},
                        inputs={bgas: Flow(nominal_value=30,
                                          variable_costs=42),
                                bcoal: Flow(nominal_value=40)},
                         conversion_factors={bgas: 0.4, bcoal: 0.6})
```

### CODE REVIEW

**Comment by simnh** [comment]
This is missing (help is appreciated) : 

* [ ] Adapt math. equation in docstring blocks-module @simnh
* [ ] Find a better name and adapt accordingly @oemof/oemof-solph 
* [ ] Add a new example or test / add to existing one and adapt test @uvchik 

Something else?

**Comment by ckaldemeyer** [comment]
> We need a new name maybe?

:+1:  Should we stay coherent here and say we have a LinearN1Transformer and Linear1NTransformer?

But doing this would break the API. One idea would be to replicate the LinearTransformer as 1N and add a deprecated to the old one.

> tested the code, but I did not push an example for now because I do not have the time...

I could add an example or rather extend an existing one. I would propose the [simple dispatch example](https://github.com/oemof/oemof/blob/dev/examples/solph/simple_dispatch/simple_dispatch.py)

Then we need to decide on a use case..

**Comment by simnh** [comment]
I guess it should be possible to add a new name and a drepreciated one without copying.. ? this should be a common problem. But then we could maybe find better names anyway... :D 

Regarding the example I was thinking of mixing-fuels or something like that...(this is the use case where I am working on right now)

**Comment by ckaldemeyer** [comment]
> I guess it should be possible to add a new name and a drepreciated one without copying.. ? this should be a common problem. But then we could maybe find better names anyway... :D

Subclassing :D

**Comment by ckaldemeyer** [comment]
> Regarding the example I was thinking of mixing-fuels or something like that...(this is the use case where I am working on right now)

I'll figure out something

**Comment by ckaldemeyer** [comment]
> Another use case is a heat pump or an heater that heats water from a colder system to hoter one. The heat pump is a special case because I use the LinearTransformer for this.

I would rather take the heatpump with let's say a constant heat source and constant cop.

**Comment by uvchik** [comment]
> I would rather take the heatpump with let's say a constant heat source and constant cop.

That is exactly what I said. You can use an 1x1 Transformer for "normal" case unless you are going to use waste heat and the heat reservoir is part of your energy system. Than you will need a 2x1 Transformer.

If you have a pressure-less storage you may need a heater for temperatures above 98°C. You will need a 2x1 Transformer for this, too.

**Comment by ckaldemeyer** [comment]
> That is exactly what I said. You can use an 1x1 Transformer for "normal" case unless you are going to use waste heat and the heat reservoir is part of your energy system. Than you will need a 2x1 Transformer.
> 
> If you have a pressure-less storage you may need a heater for temperatures above 98°C. You will need a 2x1 Transformer for this, too.

I'll make a proposal tmr.

**Comment by uvchik** [comment]
I saw that we did not have any tests for a LinearTransformer with more than one output so I added some more tests.

@simnh Could you double check if the lp-files do have the right form?

**Comment by simnh** [comment]
The lp files look good I think...

**Comment by simnh** [comment]
What about the naming? If we can find a good name, we can add this one in the next release...

**Comment by uvchik** [comment]
I will ask my colleagues for ideas. If we won't find a better name until Monday we should just use the existing one.

The new contributor generation should add an NxM Linear Transformer (chp with coal/biomass) any way :smirk:

**Comment by ckaldemeyer** [comment]
> What about the naming? If we can find a good name, we can add this one in the next release...

My preference would be to have two linear transformers or a combined one:

* LinearTransformer1N
* LinearTransformerN1
* LinearTransformerNM (which would make the first ones obsolete)

But the combined one might be a bit prone to errors, etc. and could be build from the two types anyway.

From what I know the normal way to express relations is 1:N or N:1 and N:M but the N comes before the M. Just as an idea..

And concerning the implementation we could just let the (old) LinearTransformer inherit from the new one with a deprecated warning and it's doing the same then.

**Comment by ckaldemeyer** [comment]
I am starting now to implement something in the simple dispatch example

**Comment by ckaldemeyer** [comment]
BTW I think it is really cool to have this transformer now as it was something that's been missing in consequence to the former structure

**Comment by ckaldemeyer** [comment]
I have just added the component and am finishing for today.

Generally, the HP could be represented as `Q_hp=Q_heat_source+P_compression` but I haven't done that yet with the two equations f1_in*eta_f1=f_out and f2_in*eta_f2=f_out. I'll continue tomorrow or if someone has fun in doing it, go ahead :smile:

**Comment by ckaldemeyer** [comment]
> Generally, the HP could be represented as Q_hp=Q_heat_source+P_compression but I haven't done that yet with the two equations f1_ineta_f1=f_out and f2_ineta_f2=f_out. I'll continue tomorrow or if someone has fun in doing it, go ahead

Actually I don't think that the described is possible out of the box with the equations in the M1 block or I don't get right now :)

**Comment by ckaldemeyer** [comment]
I pushed an approach. If you are fine I would clean up the example..

**Comment by uvchik** [comment]
I added a chapter to the documentation. Please review.

**Comment by ckaldemeyer** [comment]
I have adapted the docstrings since the heatpump example was taken twice and this might confuse new users. I'll adjust the example now if there are no objections!

**Comment by ckaldemeyer** [comment]
One thing: Should we adapt the name now to LinearN1Transformer before we release?

Maybe the naming would be something for the webco also ;)

**Comment by ckaldemeyer** [comment]
I have fixed the example now but did not adjust the plots. For me it is fine like this.

**Comment by ckaldemeyer** [comment]
Concerning WHATSNEW: If we add it, should we use just N1Transformer? Or should we just leave it out as it is replaced by the hidden NMTransformer anyway?

**Comment by uvchik** [comment]
I merged the dev branch to solve conflicts.

I would add this Transformer and nothing else. It depends on the discussion in #287, so I am not sure if this will be a part of the next release. In that case we need an interims solution.

**Comment by ckaldemeyer** [comment]
> I merged the dev branch to solve conflicts.
> 
> I would add this Transformer and nothing else. It depends on the discussion in #287, so I am not sure if this will be a part of the next release. In that case we need an interims solution.

I have changed the name to LinearN1Transformer now and (hopefully) adapted all related files.

But there are some merge conflicts due to the merged variable fraction transformer which I was not absolutely sure about. I could solve the imports, etc. but wasn't sure concerning the blocks and network file.

Should I just start or will you have a look?

**Comment by uvchik** [comment]
I will give it try.

**Comment by uvchik** [comment]
@ckaldemeyer : Will you fix the example tests?

**Comment by ckaldemeyer** [comment]
The conflicts should hopefully be fine now. Now I'll have a look at the tests..

**Comment by ckaldemeyer** [comment]
The error occurs for two constraint tests:

	cord@cord-Laptop:~/Programmierung/oemof/examples$ git status
	Auf Branch features/linear-m-1-transformer
	Ihr Branch ist auf dem selben Stand wie 'origin/features/linear-m-1-transformer'.
	Unversionierte Dateien:
	  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)

		solph/csv_reader/dispatch/results/

	nichts zum Commit vorgemerkt, aber es gibt unversionierte Dateien (benutzen Sie "git add" zum Versionieren)
	cord@cord-Laptop:~/Programmierung/oemof/examples$ ls -la
	insgesamt 40
	drwxrwxr-x 4 cord cord  4096 Mär 10 14:34 .
	drwxrwxr-x 7 cord cord  4096 Mär 10 14:31 ..
	-rw-rw-r-- 1 cord cord  2339 Mär 10 10:54 examples.py
	-rw-rw-r-- 1 cord cord    74 Mär 10 14:34 gurobi.log
	-rw-rw-r-- 1 cord cord     0 Nov  9 12:18 __init__.py
	-rw-rw-r-- 1 cord cord 10670 Mär 10 14:34 oemof_full_check.py
	drwxrwxr-x 2 cord cord  4096 Mär 10 14:36 __pycache__
	drwxrwxr-x 8 cord cord  4096 Mär 10 14:31 solph
	-rw-rw-r-- 1 cord cord  1379 Mär 10 10:54 test_installation.py
	cord@cord-Laptop:~/Programmierung/oemof/examples$ py3 oemof_full_check.py 
	Check Storage invest example...
	Solver log file: '/tmp/tmpzt2y9slg.cbc.log'
	Solver solution file: '/tmp/tmp5imkw6ub.pyomo.soln'
	Solver problem files: ('/tmp/tmp5imkw6ub.pyomo.lp',)
	Check Simple least costs optimization...
	Check Flexible Modelling...
	Check Dispatch model with csv reader...
	Check Investment model with csv reader...
	Check Variable CHP example...
	14:55:28-INFO-Path for logging: /home/cord/.oemof/log_files
	14:55:28-INFO-Used oemof version: 311065e6@features/linear-m-1-transformer
	14:55:28-INFO-*********************************************
	14:55:28-INFO-Simple least costs optimization
	14:55:28-INFO-Used solver: cbc
	14:55:28-INFO-Run check: Okay
	14:55:28-INFO-Result check: 13 error(s)
	14:55:28-ERROR-('b_heat_source', 'from_bus', 'heat_pump', 'val'): 1862.4843137140017 not between 309.21025635287094 and 309.8292959051289
	14:55:28-ERROR-('b_heat_source', 'to_bus', 'heat_source', 'val'): 1862.4843137140017 not between 309.21025635287094 and 309.8292959051289
	14:55:28-ERROR-('b_el', 'from_bus', 'excess', 'val'): 444.6071613199998 not between 347.6687451680701 and 348.3647786919301
	14:55:28-ERROR-('b_th', 'to_bus', 'heat_pump', 'val'): 2793.7264708619978 not between 927.6307694422293 and 929.4878880997713
	14:55:28-ERROR-('b_el', 'to_bus', 'pp_chp', 'val'): 9066.062521747983 not between 10454.472938122992 and 10475.402813874989
	14:55:28-ERROR-('lignite', 'from_bus', 'pp_lig', 'val'): 55258.6475791378 not between 55558.54590229538 and 55669.7742224201
	14:55:28-ERROR-('b_el', 'to_bus', 'pp_coal', 'val'): 35676.47565446838 not between 33689.324624438486 and 33756.770719782704
	14:55:28-ERROR-('gas', 'from_bus', 'pp_chp', 'val'): 30220.20837828982 not between 34848.24309676689 and 34918.009349212865
	14:55:28-ERROR-('b_el', 'from_bus', 'heat_pump', 'val'): 931.2421546099993 not between 618.4205130344126 and 619.6585921395865
	14:55:28-ERROR-('b_el', 'to_bus', 'pp_lig', 'val'): 22656.045354479214 not between 22779.00366770603 and 22824.60727865239
	14:55:28-ERROR-('coal', 'from_bus', 'pp_coal', 'val'): 91478.14305332716 not between 86382.92539251117 and 86555.86418208577
	14:55:28-ERROR-('b_th', 'to_bus', 'pp_chp', 'val'): 12088.083361442017 not between 13939.29725019135 and 13967.203751192734
	14:55:28-ERROR-objective: 2919760.793454955 not between 2929514.8416818315 and 2935379.7362597734
	14:55:28-INFO-*********************************************
	14:55:28-INFO-Dispatch model with csv reader
	14:55:28-INFO-Used solver: cbc
	14:55:28-INFO-Run check: Okay
	14:55:28-INFO-Result check: Okay
	14:55:28-INFO-*********************************************
	14:55:28-INFO-Storage invest example
	14:55:28-INFO-Used solver: cbc
	14:55:28-INFO-Run check: Okay
	14:55:28-INFO-Result check: Okay
	14:55:28-INFO-*********************************************
	14:55:28-INFO-Flexible Modelling
	14:55:28-INFO-Used solver: cbc
	14:55:28-INFO-Run check: Okay
	14:55:28-INFO-Result check: No results to check - Okay
	14:55:28-INFO-*********************************************
	14:55:28-INFO-Variable CHP example
	14:55:28-INFO-Used solver: cbc
	14:55:28-INFO-Run check: Okay
	14:55:28-INFO-Result check: Okay
	14:55:28-INFO-*********************************************
	14:55:28-INFO-Investment model with csv reader
	14:55:28-INFO-Used solver: cbc
	14:55:28-INFO-Run check: Okay
	14:55:28-INFO-Result check: No results to check - Okay
	....................FF...................
	======================================================================
	FAIL: Wrong constraints for fixed source + invest sink w. `summed_max`.
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/cord/.anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
	    self.test(*self.arg)
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 149, in test_fixed_source_invest_sink
	    self.compare_lp_files('fixed_source_invest_sink.lp')
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 72, in compare_lp_files
	    lineterm="")))
	AssertionError: Failed matching expected with generated lp file:
	--- tests/lp_files/fixed_source_invest_sink.lp
	+++ fixed_source_invest_sink_tmp.lp
	@@ -11,16 +11,16 @@
	 s.t.
	 
	 c_e_Bus_balance(electricityBus_0)_:
	--1 flow(electricityBus_excess_0)
	-= -12000000
	++1 flow(electricityBus_excess_0)
	+= 12000000
	 
	 c_e_Bus_balance(electricityBus_1)_:
	--1 flow(electricityBus_excess_1)
	-= -16000000
	++1 flow(electricityBus_excess_1)
	+= 16000000
	 
	 c_e_Bus_balance(electricityBus_2)_:
	--1 flow(electricityBus_excess_2)
	-= -14000000
	++1 flow(electricityBus_excess_2)
	+= 14000000
	 
	 c_u_InvestmentFlow_max(electricityBus_excess_0)_:
	 -0.80000000000000004 InvestmentFlow_invest(electricityBus_excess)

	======================================================================
	FAIL: Constraint test with a fixed source and a variable sink.
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/cord/.anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
	    self.test(*self.arg)
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 133, in test_fixed_source_variable_sink
	    self.compare_lp_files('fixed_source_variable_sink.lp')
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 72, in compare_lp_files
	    lineterm="")))
	AssertionError: Failed matching expected with generated lp file:
	--- tests/lp_files/fixed_source_variable_sink.lp
	+++ fixed_source_variable_sink_tmp.lp
	@@ -10,16 +10,16 @@
	 s.t.
	 
	 c_e_Bus_balance(electricityBus_0)_:
	--1 flow(electricityBus_excess_0)
	-= -430000
	++1 flow(electricityBus_excess_0)
	+= 430000
	 
	 c_e_Bus_balance(electricityBus_1)_:
	--1 flow(electricityBus_excess_1)
	-= -720000
	++1 flow(electricityBus_excess_1)
	+= 720000
	 
	 c_e_Bus_balance(electricityBus_2)_:
	--1 flow(electricityBus_excess_2)
	-= -290000
	++1 flow(electricityBus_excess_2)
	+= 290000
	 
	 c_e_ONE_VAR_CONSTANT:
	 ONE_VAR_CONSTANT = 1.0

	----------------------------------------------------------------------
	Ran 41 tests in 0.435s

	FAILED (failures=2)
	Some nosetests failed.See the output above for more information!
	Some example tests failed.See the output above for more information!
	cord@cord-Laptop:~/Programmierung/oemof/examples$ 

but it's not new and has been existing already on the dev-Branch since the first commit in 2017:

	cord@cord-Laptop:~/Programmierung/oemof/examples$ git checkout 291a6ccbdc466c2acfd72dd1f4d06f0ed8ab6b1b
	Note: checking out '291a6ccbdc466c2acfd72dd1f4d06f0ed8ab6b1b'.

	You are in 'detached HEAD' state. You can look around, make experimental
	changes and commit them, and you can discard any commits you make in this
	state without impacting any branches by performing another checkout.

	If you want to create a new branch to retain commits you create, you may
	do so (now or later) by using -b with the checkout command again. Example:

	  git checkout -b <new-branch-name>

	HEAD ist jetzt bei 291a6cc... Add function to merge multiple csv-files
	cord@cord-Laptop:~/Programmierung/oemof/examples$ ls -la
	insgesamt 36
	drwxrwxr-x 4 cord cord 4096 Mär 10 15:05 .
	drwxrwxr-x 7 cord cord 4096 Mär 10 15:05 ..
	-rw-rw-r-- 1 cord cord 1672 Mär 10 15:05 examples.py
	-rw-rw-r-- 1 cord cord   74 Mär 10 14:34 gurobi.log
	-rw-rw-r-- 1 cord cord    0 Nov  9 12:18 __init__.py
	-rw-rw-r-- 1 cord cord 9354 Mär 10 15:05 oemof_full_check.py
	drwxrwxr-x 2 cord cord 4096 Mär 10 14:36 __pycache__
	drwxrwxr-x 8 cord cord 4096 Mär 10 14:31 solph
	cord@cord-Laptop:~/Programmierung/oemof/examples$ py3 oemof_full_check.py 
	Check Storage invest example...
	Check Simple least costs optimization...
	Successfully finished.
	Check Flexible Modelling...
	Check Dispatch model with csv reader...
	15:05:57-INFO-Path for logging: /home/cord/.oemof/log_files
	15:05:57-INFO-Used oemof version: 0.1.2dev
	15:05:57-INFO-OM creation time: 0:00:00.04
	Welcome to the CBC MILP Solver 
	Version: 2.8.12 
	Build Date: Feb 22 2016 

	command line - /usr/bin/cbc -printingOptions all -import /tmp/tmpuq4fp8vb.pyomo.lp -import -stat=1 -solve -solu /tmp/tmpuq4fp8vb.pyomo.soln (default strategy 1)
	Option for printingOptions changed from normal to all
	Current default (if $ as parameter) for import is /tmp/tmpuq4fp8vb.pyomo.lp
	Presolve 263 (-389) rows, 272 (-340) columns and 798 (-777) elements
	Statistics for presolved model


	Problem has 263 rows, 272 columns (201 with objective) and 798 elements
	There are 48 singletons with objective 
	Column breakdown:
	272 of type 0.0->inf, 0 of type 0.0->up, 0 of type lo->inf, 
	0 of type lo->up, 0 of type free, 0 of type fixed, 
	0 of type -inf->0.0, 0 of type -inf->up, 0 of type 0.0->1.0 
	Row breakdown:
	24 of type E 0.0, 0 of type E 1.0, 0 of type E -1.0, 
	24 of type E other, 0 of type G 0.0, 0 of type G 1.0, 
	0 of type G other, 215 of type L 0.0, 0 of type L 1.0, 
	0 of type L other, 0 of type Range 0.0->1.0, 0 of type Range other, 
	0 of type Free 
	Presolve 263 (-389) rows, 272 (-340) columns and 798 (-777) elements
	Perturbing problem by 0.001 %% of 0.00011008548 - largest nonzero change 9.9878302e-06 (%% 9041.4243) - largest zero change 9.5160144e-06
	0  Obj 0 Primal inf 1024561.8 (24)
	80  Obj 13582641 Primal inf 120251.35 (18)
	123  Obj 14779272
	Optimal - objective value 14779271
	After Postsolve, objective 14779271, infeasibilities - dual 0 (0), primal 0 (0)
	Optimal objective 14779271.32 - 123 iterations time 0.002, Presolve 0.00
	Total time (CPU seconds):       0.00   (Wallclock seconds):       0.01

	15:05:57-INFO-Optimization time: 0:00:00.08
	15:05:57-INFO-Done!
	Check Investment model with csv reader...
	15:05:57-INFO-Path for logging: /home/cord/.oemof/log_files
	15:05:57-INFO-Used oemof version: 0.1.2dev
	15:05:57-INFO-*********************************************
	15:05:57-INFO-Investment model with csv reader
	15:05:57-INFO-Used solver: cbc
	15:05:57-INFO-Run check: Okay
	15:05:57-INFO-Result check: No results to check - Okay
	15:05:57-INFO-*********************************************
	15:05:57-INFO-Storage invest example
	15:05:57-INFO-Used solver: cbc
	15:05:57-INFO-Run check: Okay
	15:05:57-INFO-Result check: Okay
	15:05:57-INFO-*********************************************
	15:05:57-INFO-Flexible Modelling
	15:05:57-INFO-Used solver: cbc
	15:05:57-INFO-Run check: Okay
	15:05:57-INFO-Result check: No results to check - Okay
	15:05:57-INFO-*********************************************
	15:05:57-INFO-Simple least costs optimization
	15:05:57-INFO-Used solver: cbc
	15:05:57-INFO-Run check: Okay
	15:05:57-INFO-Result check: Okay
	15:05:57-INFO-*********************************************
	15:05:57-INFO-Dispatch model with csv reader
	15:05:57-INFO-Used solver: cbc
	15:05:57-INFO-Run check: Okay
	15:05:57-INFO-Result check: Okay
	.................FF..............
	======================================================================
	FAIL: Wrong constraints for fixed source + invest sink w. `summed_max`.
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/cord/.anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
	    self.test(*self.arg)
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 146, in test_fixed_source_invest_sink
	    self.compare_lp_files('fixed_source_invest_sink.lp')
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 70, in compare_lp_files
	    lineterm="")))
	AssertionError: Failed matching expected with generated lp file:
	--- tests/lp_files/fixed_source_invest_sink.lp
	+++ fixed_source_invest_sink_tmp.lp
	@@ -11,16 +11,16 @@
	 s.t.
	 
	 c_e_Bus_balance(electricityBus_0)_:
	--1 flow(electricityBus_excess_0)
	-= -12000000
	++1 flow(electricityBus_excess_0)
	+= 12000000
	 
	 c_e_Bus_balance(electricityBus_1)_:
	--1 flow(electricityBus_excess_1)
	-= -16000000
	++1 flow(electricityBus_excess_1)
	+= 16000000
	 
	 c_e_Bus_balance(electricityBus_2)_:
	--1 flow(electricityBus_excess_2)
	-= -14000000
	++1 flow(electricityBus_excess_2)
	+= 14000000
	 
	 c_u_InvestmentFlow_max(electricityBus_excess_0)_:
	 -0.80000000000000004 InvestmentFlow_invest(electricityBus_excess)

	======================================================================
	FAIL: Constraint test with a fixed source and a variable sink.
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/cord/.anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
	    self.test(*self.arg)
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 130, in test_fixed_source_variable_sink
	    self.compare_lp_files('fixed_source_variable_sink.lp')
	  File "/home/cord/Programmierung/oemof/tests/constraint_tests.py", line 70, in compare_lp_files
	    lineterm="")))
	AssertionError: Failed matching expected with generated lp file:
	--- tests/lp_files/fixed_source_variable_sink.lp
	+++ fixed_source_variable_sink_tmp.lp
	@@ -10,16 +10,16 @@
	 s.t.
	 
	 c_e_Bus_balance(electricityBus_0)_:
	--1 flow(electricityBus_excess_0)
	-= -430000
	++1 flow(electricityBus_excess_0)
	+= 430000
	 
	 c_e_Bus_balance(electricityBus_1)_:
	--1 flow(electricityBus_excess_1)
	-= -720000
	++1 flow(electricityBus_excess_1)
	+= 720000
	 
	 c_e_Bus_balance(electricityBus_2)_:
	--1 flow(electricityBus_excess_2)
	-= -290000
	++1 flow(electricityBus_excess_2)
	+= 290000
	 
	 c_e_ONE_VAR_CONSTANT:
	 ONE_VAR_CONSTANT = 1.0

	----------------------------------------------------------------------
	Ran 33 tests in 0.132s

	FAILED (failures=2)
	Some nosetests failed.See the output above for more information!
	All example tests passed!
	cord@cord-Laptop:~/Programmierung/oemof/examples$ 

I guess the best way to track it down would be to hop backwards in the branch history and see where it occured first wouldn't it? Kind of bisecting the whole thing..I'll look further..

**Comment by ckaldemeyer** [comment]
> 15:05:57-INFO-Used oemof version: 0.1.2dev

Obviously it didn't really use the commit I jumped to. Weird, I'll have a look..

**Comment by ckaldemeyer** [comment]
The error occured with the following [commit](https://github.com/oemof/oemof/commit/6f4edfa10f88f172dcb48071c5dc5261d8922219) which was meant to fix the creaking pyomo tests by changing the LP files.

To me they look allright from the content (and bla=bla is equal to -bla=-bla) but the check fails if pyomo writes the LP file not in the same style as the one on the file system/branch in `tests/lp_files`.

I think we could fix it by creating a new lp file and substituting it with the one on the branch.

@uvchik : Do you remember why you changed it?

**Comment by ckaldemeyer** [comment]
As the error has been existing in the dev-Branch for longer anyway, I'll merge this branch already..

**Comment by ckaldemeyer** [comment]
#290

**Pull request merged**
