### PR TITLE
Make solph.GROUPINGS a default parameter

### PR DESCRIPTION
**Pull request by uvchik**
According to #214.

### CODE REVIEW

**Comment by simnh** [comment]
I dont think taht is actually i really good solution. EnergySystem rather belongs to network...But am not an expert. I think @gnn  should suggest a solution, or at least comment on this.

**Comment by uvchik** [comment]
I would say that the network is part of the EnergySystem as groupings is part of the EnergySystem. So I couldn't say where to put it. Maybe outside both of them, 'plumbing` would be an alternative place without circular imports. Than I could rename it again to groupings.

> I think @gnn should suggest a solution, or at least comment on this.
I agree on that. That's why I created a PR and did not change it right away.

**Comment by uvchik** [comment]
For me it is okay like this. If @simnh agrees you can merge it (solve the merge conflicts :smirk:)

**Comment by simnh** [comment]
go ahead...

**Comment by uvchik** [comment]
@gnn: I fixed the merge conflicts. Please merge if you agree.

In the whatsnew file you wrote about changes to the groupings API but there was no groupings API at the previous version (v0.0.7). Please have a look at the whatsnew file and please merge until tomorrow.

**Comment by gnn** [comment]
The groupings API has been there since version 0.0.5, when it was mentioned in the features of whatsnew. ;) But since we are doing kind of a major release, I can remove the parts taking care of backwards compatibility now.
Also, why did you delete v-0.1.rst without copying the changes I made over to v-0.1.0.rst? Or maybe git did delete that when merging recursively. I gotta keep an eye on those cases. Don't want to loose any work when merging.
And why is `solph.GROUPINGS` still used in the [storage invest example](https://github.com/oemof/oemof/pull/215/commits/b20def518f3885a7f13eae0a6a0af736a78a46fc#diff-2ba9caf8eb44df8151fa8f893b86a82eR56)? I thought the whole point of this PR was to not have to specify it when creating the energy system.
I'm going to fix the two points mentioned. Otherwise, this looks good to me.

**Comment by uvchik** [comment]
> Also, why did you delete v-0.1.rst without copying the changes I made over to v-0.1.0.rst? Or maybe git did delete that when merging recursively. I gotta keep an eye on those cases. Don't want to loose any work when merging.

Sorry @gnn this my fault not a git issue. God confused with the two different entries regarding the grouping issues. Thanks to git your work is not lost (s. below). Do you want me to copy this into the whatsnew file?
```
* Solph's :class:`EnergySystem <oemof.solph.network.EnergySystem>` now
  automatically uses solph's :const:`GROUPINGS
  <oemof.solph.groupings.GROUPINGS>` in addition to any user supplied ones.
  See the API documentation for more information.
```

> And why is solph.GROUPINGS still used in the storage invest example? I thought the whole point of this PR was to not have to specify it when creating the energy system.

Also my fault. You are right that was the point. I changed it in the documentation but forgot to remove it from the examples. With b21d142 I removed it from all examples.

My tests passed and Travis CI seems to be happy, too. Thanks a lot for you work and feel free to merge.

**Comment by uvchik** [comment]
P.S.: I saw you already copied it to the whatsnew file.

**Comment by uvchik** [comment]
@gnn Thank you for fixing it :sunflower:

**Pull request merged**
